In [1]:
import pandas as pd

### Reading Data in CSV or Text files

In [3]:
df = pd.read_csv("/Users/cwbenton/MATH4140/datasets/supermarket_sales.csv")
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [184]:
#doing this will add index as an extra column
df.to_csv("datasets/market_sales.csv")
df2 = pd.read_csv("datasets/market_sales.csv")
df2

,Unnamed: 0,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [185]:
#set it right
#df.to_csv("market_sales.csv",index=False)
df2 = pd.read_csv("market_sales.csv",index_col=0)
#Use a header option?
df2

,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
Invoice ID,,,,,,,,,,,,,,,,
750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [186]:
#use other delimiters with read_table
df3 = pd.read_table("datasets/fra.txt",sep="\t")
df3

,Go.,Va !
0,Hi.,Salut !
1,Run!,Cours !
2,Run!,Courez !
3,Wow!,Ça alors !
4,Fire!,Au feu !
...,...,...
160532,A carbon footprint is the amount of carbon dio...,Une empreinte carbone est la somme de pollutio...
160533,Death is something that we're often discourage...,La mort est une chose qu'on nous décourage sou...
160534,Since there are usually multiple websites on a...,Puisqu'il y a de multiples sites web sur chaqu...
160535,If someone who doesn't know your background sa...,Si quelqu'un qui ne connaît pas vos antécédent...
160536,It may be impossible to get a completely error...,Il est peut-être impossible d'obtenir un Corpu...

### Reading and Writing Data on Microsoft Excel Files

In [187]:
df4 = pd.read_excel("datasets/njs2016_dd_en.xlsx")
df4

,NAME,LABEL,Answer Code,Explanation for Answer Code
0,CONF_AD,Confidence in Adult criminal law in Canada- Raw,1,No Confidence
1,CONF_AD,Confidence in Adult criminal law in Canada- Raw,2,2
2,CONF_AD,Confidence in Adult criminal law in Canada- Raw,3,3
3,CONF_AD,Confidence in Adult criminal law in Canada- Raw,4,4
4,CONF_AD,Confidence in Adult criminal law in Canada- Raw,5,Moderate cofidence
...,...,...,...,...
1862,w2age,Computed age categories,5,55-64
1863,w2age,Computed age categories,6,65+
1864,w2age,Computed age categories,9,No response
1865,DEMO_S1RECRUIT,NaN,1,Yes
1866,DEMO_S1RECRUIT,NaN,0,No

In [188]:
df4.head()

,NAME,LABEL,Answer Code,Explanation for Answer Code
0,CONF_AD,Confidence in Adult criminal law in Canada- Raw,1,No Confidence
1,CONF_AD,Confidence in Adult criminal law in Canada- Raw,2,2
2,CONF_AD,Confidence in Adult criminal law in Canada- Raw,3,3
3,CONF_AD,Confidence in Adult criminal law in Canada- Raw,4,4
4,CONF_AD,Confidence in Adult criminal law in Canada- Raw,5,Moderate cofidence

In [189]:
df4.tail()

,NAME,LABEL,Answer Code,Explanation for Answer Code
1862,w2age,Computed age categories,5,55-64
1863,w2age,Computed age categories,6,65+
1864,w2age,Computed age categories,9,No response
1865,DEMO_S1RECRUIT,NaN,1,Yes
1866,DEMO_S1RECRUIT,NaN,0,No

In [190]:
df4.head(10)

,NAME,LABEL,Answer Code,Explanation for Answer Code
0,CONF_AD,Confidence in Adult criminal law in Canada- Raw,1,No Confidence
1,CONF_AD,Confidence in Adult criminal law in Canada- Raw,2,2
2,CONF_AD,Confidence in Adult criminal law in Canada- Raw,3,3
3,CONF_AD,Confidence in Adult criminal law in Canada- Raw,4,4
4,CONF_AD,Confidence in Adult criminal law in Canada- Raw,5,Moderate cofidence
5,CONF_AD,Confidence in Adult criminal law in Canada- Raw,6,6
6,CONF_AD,Confidence in Adult criminal law in Canada- Raw,7,7
7,CONF_AD,Confidence in Adult criminal law in Canada- Raw,8,8
8,CONF_AD,Confidence in Adult criminal law in Canada- Raw,9,9
9,CONF_AD,Confidence in Adult criminal law in Canada- Raw,10,A great deal of confidence

### Reading and Writing Data on json Files

In [191]:
df5 = pd.read_json("datasets/iris.json")
df5

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

### Reading and Writing Data on pickle Files

In [192]:
import pickle as pkl

In [193]:
pkl_data = pkl.dumps(df5)

In [194]:
print(pkl_data)

b'\x80\x04\x95[\x1c\x00\x00\x00\x00\x00\x00\x8c\x11pandas.core.frame\x94\x8c\tDataFrame\x94\x93\x94)\x81\x94}\x94(\x8c\x04_mgr\x94\x8c\x1epandas.core.internals.managers\x94\x8c\x0cBlockManager\x94\x93\x94\x8c\x16pandas._libs.internals\x94\x8c\x0f_unpickle_block\x94\x93\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x04K\x96\x86\x94h\x0f\x8c\x05dtype\x94\x93\x94\x8c\x02f8\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89B\xc0\x12\x00\x00ffffff\x14@\x9a\x99\x99\x99\x99\x99\x13@\xcd\xcc\xcc\xcc\xcc\xcc\x12@ffffff\x12@\x00\x00\x00\x00\x00\x00\x14@\x9a\x99\x99\x99\x99\x99\x15@ffffff\x12@\x00\x00\x00\x00\x00\x00\x14@\x9a\x99\x99\x99\x99\x99\x11@\x9a\x99\x99\x99\x99\x99\x13@\x9a\x99\x99\x99\x99\x99\x15@333333\x13@333333\x13@333333\x11@333333\x17@\xcd\xcc\xcc\xcc\xcc\xcc\x16@\x9a\x99\x99\x99\x99\x99\x15@ffffff\x14@\xcd\xcc\xcc\xcc\xcc\xcc\x16@ffffff\x14@\x9a\x99\x99\x99\x99\x99\x15@ffffff\x14@ffffff\x12@ffffff\x14@333333\x13@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x14@\xcd\xcc\xcc\xcc\xcc\xcc\x14@\xcd\xcc\xcc\xcc\xcc\xcc\x14@\xcd\xcc\xcc\xcc\xcc\xcc\x12@333333\x13@\x9a\x99\x99\x99\x99\x99\x15@\xcd\xcc\xcc\xcc\xcc\xcc\x14@\x00\x00\x00\x00\x00\x00\x16@\x9a\x99\x99\x99\x99\x99\x13@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x16@\x9a\x99\x99\x99\x99\x99\x13@\x9a\x99\x99\x99\x99\x99\x11@ffffff\x14@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x12@\x9a\x99\x99\x99\x99\x99\x11@\x00\x00\x00\x00\x00\x00\x14@ffffff\x14@333333\x13@ffffff\x14@ffffff\x12@333333\x15@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x1c@\x9a\x99\x99\x99\x99\x99\x19@\x9a\x99\x99\x99\x99\x99\x1b@\x00\x00\x00\x00\x00\x00\x16@\x00\x00\x00\x00\x00\x00\x1a@\xcd\xcc\xcc\xcc\xcc\xcc\x16@333333\x19@\x9a\x99\x99\x99\x99\x99\x13@ffffff\x1a@\xcd\xcc\xcc\xcc\xcc\xcc\x14@\x00\x00\x00\x00\x00\x00\x14@\x9a\x99\x99\x99\x99\x99\x17@\x00\x00\x00\x00\x00\x00\x18@ffffff\x18@ffffff\x16@\xcd\xcc\xcc\xcc\xcc\xcc\x1a@ffffff\x16@333333\x17@\xcd\xcc\xcc\xcc\xcc\xcc\x18@ffffff\x16@\x9a\x99\x99\x99\x99\x99\x17@ffffff\x18@333333\x19@ffffff\x18@\x9a\x99\x99\x99\x99\x99\x19@ffffff\x1a@333333\x1b@\xcd\xcc\xcc\xcc\xcc\xcc\x1a@\x00\x00\x00\x00\x00\x00\x18@\xcd\xcc\xcc\xcc\xcc\xcc\x16@\x00\x00\x00\x00\x00\x00\x16@\x00\x00\x00\x00\x00\x00\x16@333333\x17@\x00\x00\x00\x00\x00\x00\x18@\x9a\x99\x99\x99\x99\x99\x15@\x00\x00\x00\x00\x00\x00\x18@\xcd\xcc\xcc\xcc\xcc\xcc\x1a@333333\x19@ffffff\x16@\x00\x00\x00\x00\x00\x00\x16@\x00\x00\x00\x00\x00\x00\x16@ffffff\x18@333333\x17@\x00\x00\x00\x00\x00\x00\x14@ffffff\x16@\xcd\xcc\xcc\xcc\xcc\xcc\x16@\xcd\xcc\xcc\xcc\xcc\xcc\x16@\xcd\xcc\xcc\xcc\xcc\xcc\x18@ffffff\x14@\xcd\xcc\xcc\xcc\xcc\xcc\x16@333333\x19@333333\x17@ffffff\x1c@333333\x19@\x00\x00\x00\x00\x00\x00\x1a@ffffff\x1e@\x9a\x99\x99\x99\x99\x99\x13@333333\x1d@\xcd\xcc\xcc\xcc\xcc\xcc\x1a@\xcd\xcc\xcc\xcc\xcc\xcc\x1c@\x00\x00\x00\x00\x00\x00\x1a@\x9a\x99\x99\x99\x99\x99\x19@333333\x1b@\xcd\xcc\xcc\xcc\xcc\xcc\x16@333333\x17@\x9a\x99\x99\x99\x99\x99\x19@\x00\x00\x00\x00\x00\x00\x1a@\xcd\xcc\xcc\xcc\xcc\xcc\x1e@\xcd\xcc\xcc\xcc\xcc\xcc\x1e@\x00\x00\x00\x00\x00\x00\x18@\x9a\x99\x99\x99\x99\x99\x1b@ffffff\x16@\xcd\xcc\xcc\xcc\xcc\xcc\x1e@333333\x19@\xcd\xcc\xcc\xcc\xcc\xcc\x1a@\xcd\xcc\xcc\xcc\xcc\xcc\x1c@\xcd\xcc\xcc\xcc\xcc\xcc\x18@ffffff\x18@\x9a\x99\x99\x99\x99\x99\x19@\xcd\xcc\xcc\xcc\xcc\xcc\x1c@\x9a\x99\x99\x99\x99\x99\x1d@\x9a\x99\x99\x99\x99\x99\x1f@\x9a\x99\x99\x99\x99\x99\x19@333333\x19@ffffff\x18@\xcd\xcc\xcc\xcc\xcc\xcc\x1e@333333\x19@\x9a\x99\x99\x99\x99\x99\x19@\x00\x00\x00\x00\x00\x00\x18@\x9a\x99\x99\x99\x99\x99\x1b@\xcd\xcc\xcc\xcc\xcc\xcc\x1a@\x9a\x99\x99\x99\x99\x99\x1b@333333\x17@333333\x1b@\xcd\xcc\xcc\xcc\xcc\xcc\x1a@\xcd\xcc\xcc\xcc\xcc\xcc\x1a@333333\x19@\x00\x00\x00\x00\x00\x00\x1a@\xcd\xcc\xcc\xcc\xcc\xcc\x18@\x9a\x99\x99\x99\x99\x99\x17@\x00\x00\x00\x00\x00\x00\x0c@\x00\x00\x00\x00\x00\x00\x08@\x9a\x99\x99\x99\x99\x99\t@\xcd\xcc\xcc\xcc\xcc\xcc\x08@\xcd\xcc\xcc\xcc\xcc\xcc\x0c@333333\x0f@333333\x0b@333333\x0b@333333\x07@\xcd\xcc\xcc\xcc\xcc\xcc\x08@\x9a\x99\x99\x99\x99\x99\r@333333\x0b@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x9a\x99\x99\x99\x99\x99\x11@333333\x0f@\x00\x00\x00\x00\x00\x00\x0c@ffffff\x0e@ffffff\x0e@333333\x0b@\x9a\x99\x99\x99\x99\x99\r@\xcd\xcc\xcc\xcc\xcc\xcc\x0c@ffffff\n@333333\x0b@\x00\x00\x00\x00\x00\x00\x08@333333\x0b@\x00\x00\x00\x00\x00\x00\x0c@333333\x0b@\x9a\x99\x99\x99\x99\x99\t@\xcd\xcc\xcc\xcc\xcc\xcc\x08@333333\x0b@ffffff\x10@\xcd\xcc\xcc\xcc\xcc\xcc\x10@\xcd\xcc\xcc\xcc\xcc\xcc\x08@\x9a\x99\x99\x99\x99\x99\t@\x00\x00\x00\x00\x00\x00\x0c@\xcd\xcc\xcc\xcc\xcc\xcc\x0c@\x00\x00\x00\x00\x00\x00\x08@333333\x0b@\x00\x00\x00\x00\x00\x00\x0c@ffffff\x02@\x9a\x99\x99\x99\x99\x99\t@\x00\x00\x00\x00\x00\x00\x0c@ffffff\x0e@\x00\x00\x00\x00\x00\x00\x08@ffffff\x0e@\x9a\x99\x99\x99\x99\x99\t@\x9a\x99\x99\x99\x99\x99\r@ffffff\n@\x9a\x99\x99\x99\x99\x99\t@\x9a\x99\x99\x99\x99\x99\t@\xcd\xcc\xcc\xcc\xcc\xcc\x08@ffffff\x02@ffffff\x06@ffffff\x06@ffffff\n@333333\x03@333333\x07@\x9a\x99\x99\x99\x99\x99\x05@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x9a\x99\x99\x99\x99\x99\x01@333333\x07@333333\x07@\xcd\xcc\xcc\xcc\xcc\xcc\x08@\x00\x00\x00\x00\x00\x00\x08@\x9a\x99\x99\x99\x99\x99\x05@\x9a\x99\x99\x99\x99\x99\x01@\x00\x00\x00\x00\x00\x00\x04@\x9a\x99\x99\x99\x99\x99\t@ffffff\x06@\x00\x00\x00\x00\x00\x00\x04@ffffff\x06@333333\x07@\x00\x00\x00\x00\x00\x00\x08@ffffff\x06@\x00\x00\x00\x00\x00\x00\x08@333333\x07@\xcd\xcc\xcc\xcc\xcc\xcc\x04@333333\x03@333333\x03@\x9a\x99\x99\x99\x99\x99\x05@\x9a\x99\x99\x99\x99\x99\x05@\x00\x00\x00\x00\x00\x00\x08@333333\x0b@\xcd\xcc\xcc\xcc\xcc\xcc\x08@ffffff\x02@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x04@\xcd\xcc\xcc\xcc\xcc\xcc\x04@\x00\x00\x00\x00\x00\x00\x08@\xcd\xcc\xcc\xcc\xcc\xcc\x04@ffffff\x02@\x9a\x99\x99\x99\x99\x99\x05@\x00\x00\x00\x00\x00\x00\x08@333333\x07@333333\x07@\x00\x00\x00\x00\x00\x00\x04@ffffff\x06@ffffff\n@\x9a\x99\x99\x99\x99\x99\x05@\x00\x00\x00\x00\x00\x00\x08@333333\x07@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x04@333333\x07@\x00\x00\x00\x00\x00\x00\x04@\xcd\xcc\xcc\xcc\xcc\xcc\x0c@\x9a\x99\x99\x99\x99\x99\t@\x9a\x99\x99\x99\x99\x99\x05@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x04@ffffff\x06@\x9a\x99\x99\x99\x99\x99\t@\x00\x00\x00\x00\x00\x00\x08@ffffff\x0e@\xcd\xcc\xcc\xcc\xcc\xcc\x04@\x9a\x99\x99\x99\x99\x99\x01@\x9a\x99\x99\x99\x99\x99\t@ffffff\x06@ffffff\x06@\x9a\x99\x99\x99\x99\x99\x05@ffffff\n@\x9a\x99\x99\x99\x99\x99\t@ffffff\x06@\x00\x00\x00\x00\x00\x00\x08@ffffff\x06@\x00\x00\x00\x00\x00\x00\x08@ffffff\x06@ffffff\x0e@ffffff\x06@ffffff\x06@\xcd\xcc\xcc\xcc\xcc\xcc\x04@\x00\x00\x00\x00\x00\x00\x08@333333\x0b@\xcd\xcc\xcc\xcc\xcc\xcc\x08@\x00\x00\x00\x00\x00\x00\x08@\xcd\xcc\xcc\xcc\xcc\xcc\x08@\xcd\xcc\xcc\xcc\xcc\xcc\x08@\xcd\xcc\xcc\xcc\xcc\xcc\x08@\x9a\x99\x99\x99\x99\x99\x05@\x9a\x99\x99\x99\x99\x99\t@ffffff\n@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x04@\x00\x00\x00\x00\x00\x00\x08@333333\x0b@\x00\x00\x00\x00\x00\x00\x08@ffffff\xf6?ffffff\xf6?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\x00\x00\x00\x00\x00\x00\xf8?ffffff\xf6?433333\xfb?ffffff\xf6?\x00\x00\x00\x00\x00\x00\xf8?ffffff\xf6?\x00\x00\x00\x00\x00\x00\xf8?\x00\x00\x00\x00\x00\x00\xf8?\x9a\x99\x99\x99\x99\x99\xf9?ffffff\xf6?\x9a\x99\x99\x99\x99\x99\xf1?333333\xf3?\x00\x00\x00\x00\x00\x00\xf8?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?ffffff\xf6?433333\xfb?\x00\x00\x00\x00\x00\x00\xf8?433333\xfb?\x00\x00\x00\x00\x00\x00\xf8?\x00\x00\x00\x00\x00\x00\xf0?433333\xfb?ffffff\xfe?\x9a\x99\x99\x99\x99\x99\xf9?\x9a\x99\x99\x99\x99\x99\xf9?\x00\x00\x00\x00\x00\x00\xf8?ffffff\xf6?\x9a\x99\x99\x99\x99\x99\xf9?\x9a\x99\x99\x99\x99\x99\xf9?\x00\x00\x00\x00\x00\x00\xf8?\x00\x00\x00\x00\x00\x00\xf8?ffffff\xf6?\x00\x00\x00\x00\x00\x00\xf8?333333\xf3?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?ffffff\xf6?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\x00\x00\x00\x00\x00\x00\xf8?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\x9a\x99\x99\x99\x99\x99\xf9?ffffff\xfe?ffffff\xf6?\x9a\x99\x99\x99\x99\x99\xf9?ffffff\xf6?\x00\x00\x00\x00\x00\x00\xf8?ffffff\xf6?\xcd\xcc\xcc\xcc\xcc\xcc\x12@\x00\x00\x00\x00\x00\x00\x12@\x9a\x99\x99\x99\x99\x99\x13@\x00\x00\x00\x00\x00\x00\x10@ffffff\x12@\x00\x00\x00\x00\x00\x00\x12@\xcd\xcc\xcc\xcc\xcc\xcc\x12@ffffff\n@ffffff\x12@333333\x0f@\x00\x00\x00\x00\x00\x00\x0c@\xcd\xcc\xcc\xcc\xcc\xcc\x10@\x00\x00\x00\x00\x00\x00\x10@\xcd\xcc\xcc\xcc\xcc\xcc\x12@\xcd\xcc\xcc\xcc\xcc\xcc\x0c@\x9a\x99\x99\x99\x99\x99\x11@\x00\x00\x00\x00\x00\x00\x12@ffffff\x10@\x00\x00\x00\x00\x00\x00\x12@333333\x0f@333333\x13@\x00\x00\x00\x00\x00\x00\x10@\x9a\x99\x99\x99\x99\x99\x13@\xcd\xcc\xcc\xcc\xcc\xcc\x12@333333\x11@\x9a\x99\x99\x99\x99\x99\x11@333333\x13@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x12@\x00\x00\x00\x00\x00\x00\x0c@ffffff\x0e@\x9a\x99\x99\x99\x99\x99\r@333333\x0f@ffffff\x14@\x00\x00\x00\x00\x00\x00\x12@\x00\x00\x00\x00\x00\x00\x12@\xcd\xcc\xcc\xcc\xcc\xcc\x12@\x9a\x99\x99\x99\x99\x99\x11@ffffff\x10@\x00\x00\x00\x00\x00\x00\x10@\x9a\x99\x99\x99\x99\x99\x11@ffffff\x12@\x00\x00\x00\x00\x00\x00\x10@ffffff\n@\xcd\xcc\xcc\xcc\xcc\xcc\x10@\xcd\xcc\xcc\xcc\xcc\xcc\x10@\xcd\xcc\xcc\xcc\xcc\xcc\x10@333333\x11@\x00\x00\x00\x00\x00\x00\x08@ffffff\x10@\x00\x00\x00\x00\x00\x00\x18@ffffff\x14@\x9a\x99\x99\x99\x99\x99\x17@ffffff\x16@333333\x17@ffffff\x1a@\x00\x00\x00\x00\x00\x00\x12@333333\x19@333333\x17@ffffff\x18@ffffff\x14@333333\x15@\x00\x00\x00\x00\x00\x00\x16@\x00\x00\x00\x00\x00\x00\x14@ffffff\x14@333333\x15@\x00\x00\x00\x00\x00\x00\x16@\xcd\xcc\xcc\xcc\xcc\xcc\x1a@\x9a\x99\x99\x99\x99\x99\x1b@\x00\x00\x00\x00\x00\x00\x14@\xcd\xcc\xcc\xcc\xcc\xcc\x16@\x9a\x99\x99\x99\x99\x99\x13@\xcd\xcc\xcc\xcc\xcc\xcc\x1a@\x9a\x99\x99\x99\x99\x99\x13@\xcd\xcc\xcc\xcc\xcc\xcc\x16@\x00\x00\x00\x00\x00\x00\x18@333333\x13@\x9a\x99\x99\x99\x99\x99\x13@ffffff\x16@333333\x17@ffffff\x18@\x9a\x99\x99\x99\x99\x99\x19@ffffff\x16@ffffff\x14@ffffff\x16@ffffff\x18@ffffff\x16@\x00\x00\x00\x00\x00\x00\x16@333333\x13@\x9a\x99\x99\x99\x99\x99\x15@ffffff\x16@ffffff\x14@ffffff\x14@\x9a\x99\x99\x99\x99\x99\x17@\xcd\xcc\xcc\xcc\xcc\xcc\x16@\xcd\xcc\xcc\xcc\xcc\xcc\x14@\x00\x00\x00\x00\x00\x00\x14@\xcd\xcc\xcc\xcc\xcc\xcc\x14@\x9a\x99\x99\x99\x99\x99\x15@ffffff\x14@\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xd9?433333\xd3?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xb9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xb9?\x9a\x99\x99\x99\x99\x99\xb9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xd9?\x9a\x99\x99\x99\x99\x99\xd9?433333\xd3?433333\xd3?433333\xd3?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xd9?\x9a\x99\x99\x99\x99\x99\xc9?\x00\x00\x00\x00\x00\x00\xe0?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xd9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xd9?\x9a\x99\x99\x99\x99\x99\xb9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xb9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?433333\xd3?433333\xd3?\x9a\x99\x99\x99\x99\x99\xc9?433333\xe3?\x9a\x99\x99\x99\x99\x99\xd9?433333\xd3?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xc9?ffffff\xf6?\x00\x00\x00\x00\x00\x00\xf8?\x00\x00\x00\x00\x00\x00\xf8?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\x00\x00\x00\x00\x00\x00\xf8?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\x9a\x99\x99\x99\x99\x99\xf9?\x00\x00\x00\x00\x00\x00\xf0?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?ffffff\xf6?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf8?\x00\x00\x00\x00\x00\x00\xf0?ffffff\xf6?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?ffffff\xf6?\x00\x00\x00\x00\x00\x00\xf8?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf8?\x9a\x99\x99\x99\x99\x99\xf1?\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\x00\x00\x00\x00\x00\x00\xf8?333333\xf3?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?ffffff\xf6?ffffff\xf6?433333\xfb?\x00\x00\x00\x00\x00\x00\xf8?\x00\x00\x00\x00\x00\x00\xf0?\x9a\x99\x99\x99\x99\x99\xf1?\x00\x00\x00\x00\x00\x00\xf0?333333\xf3?\x9a\x99\x99\x99\x99\x99\xf9?\x00\x00\x00\x00\x00\x00\xf8?\x9a\x99\x99\x99\x99\x99\xf9?\x00\x00\x00\x00\x00\x00\xf8?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?333333\xf3?ffffff\xf6?333333\xf3?\x00\x00\x00\x00\x00\x00\xf0?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?333333\xf3?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\x9a\x99\x99\x99\x99\x99\xf1?\xcd\xcc\xcc\xcc\xcc\xcc\xf4?\x00\x00\x00\x00\x00\x00\x04@ffffff\xfe?\xcd\xcc\xcc\xcc\xcc\xcc\x00@\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\x9a\x99\x99\x99\x99\x99\x01@\xcd\xcc\xcc\xcc\xcc\xcc\x00@433333\xfb?\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\x00\x00\x00\x00\x00\x00\x04@\x00\x00\x00\x00\x00\x00\x00@ffffff\xfe?\xcd\xcc\xcc\xcc\xcc\xcc\x00@\x00\x00\x00\x00\x00\x00\x00@333333\x03@ffffff\x02@\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\x9a\x99\x99\x99\x99\x99\x01@ffffff\x02@\x00\x00\x00\x00\x00\x00\xf8?ffffff\x02@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\xcd\xcc\xcc\xcc\xcc\xcc\x00@\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\xcd\xcc\xcc\xcc\xcc\xcc\x00@\x9a\x99\x99\x99\x99\x99\xf9?ffffff\xfe?\x00\x00\x00\x00\x00\x00\x00@\x9a\x99\x99\x99\x99\x99\x01@\x00\x00\x00\x00\x00\x00\xf8?ffffff\xf6?ffffff\x02@333333\x03@\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\xcd\xcc\xcc\xcc\xcc\xcc\x00@333333\x03@ffffff\x02@ffffff\xfe?ffffff\x02@\x00\x00\x00\x00\x00\x00\x04@ffffff\x02@ffffff\xfe?\x00\x00\x00\x00\x00\x00\x00@ffffff\x02@\xcd\xcc\xcc\xcc\xcc\xcc\xfc?\x94t\x94b\x8c\x08builtins\x94\x8c\x05slice\x94\x93\x94K\x00K\x04K\x01\x87\x94R\x94K\x02\x87\x94R\x94h\x0bh\x0eh\x11K\x00\x85\x94h\x13\x87\x94R\x94(K\x01K\x01K\x96\x86\x94h\x18\x8c\x02O8\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01|\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK?t\x94b\x89]\x94(\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\x06setosa\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\nversicolor\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94\x8c\tvirginica\x94et\x94bh"K\x04K\x05K\x01\x87\x94R\x94K\x02\x87\x94R\x94\x86\x94]\x94(\x8c\x18pandas.core.indexes.base\x94\x8c\n_new_Index\x94\x93\x94h\xce\x8c\x05Index\x94\x93\x94}\x94(\x8c\x04data\x94h\x0eh\x11K\x00\x85\x94h\x13\x87\x94R\x94(K\x01K\x05\x85\x94h-\x89]\x94(\x8c\x0bsepalLength\x94\x8c\nsepalWidth\x94\x8c\x0bpetalLength\x94\x8c\npetalWidth\x94\x8c\x07species\x94et\x94b\x8c\x04name\x94Nu\x86\x94R\x94h\xd0\x8c\x19pandas.core.indexes.range\x94\x8c\nRangeIndex\x94\x93\x94}\x94(h\xe0N\x8c\x05start\x94K\x00\x8c\x04stop\x94K\x96\x8c\x04step\x94K\x01u\x86\x94R\x94e\x86\x94R\x94\x8c\x04_typ\x94\x8c\tdataframe\x94\x8c\t_metadata\x94]\x94\x8c\x05attrs\x94}\x94\x8c\x06_flags\x94}\x94\x8c\x17allows_duplicate_labels\x94\x88sub.'

In [195]:
print(pkl.loads(pkl_data))

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

## Data Manipulation

### Data Preparation

### loading
Even after loading from different data sources, data needs further preparation

### Assembling

###### Merging
Similar to the join operation in SQL <br/>
Used to get data from different sources and combine them

In [196]:
df_freq1 = pd.read_csv("datasets/yo_frequency_list.csv")
df_freq2 = pd.read_csv("datasets/st_frequency_list.csv")
df_freq1

     freq       word
0      86          ó
1      45         ní
2      35      ìjàpá
3      33         ṣe
4      33        rẹ̀
..    ...        ...
371     1        aga
372     1        ọwọ
373     1  ọ̀pọ̀lọpọ
374     1      abúlé
375     1    ọ̀ọ́kán

[376 rows x 2 columns]

In [197]:
df_freq2

     freq     word
0     207        a
1     143       le
2     110        o
3     109       ba
4     100       ho
..    ...      ...
970     1      abe
971     1      two
972     1    aaaah
973     1       aa
974     1  utloisa

[975 rows x 2 columns]

In [198]:
pd.merge(df_freq1,df_freq2)
#gives us the rows that are common across both the dataframes

   freq word
0     1  ore
1     1   tu

In [199]:
pd.merge(df_freq1,df_freq2,on="word")

   freq_x   word  freq_y
0      16      o     110
1       9      a     207
2       4     mo      15
3       4  kenya       1
4       1    ore       1
5       1     na      10
6       1     ra       2
7       1     le     143
8       1     tu       1

In [200]:
pd.merge(df_freq1,df_freq2,on="word",how="inner")

   freq_x   word  freq_y
0      16      o     110
1       9      a     207
2       4     mo      15
3       4  kenya       1
4       1    ore       1
5       1     na      10
6       1     ra       2
7       1     le     143
8       1     tu       1

In [201]:
pd.merge(df_freq1,df_freq2,on="word",how="outer")

      freq_x     word  freq_y
0       86.0        ó     NaN
1       45.0       ní     NaN
2       35.0    ìjàpá     NaN
3       33.0       ṣe     NaN
4       33.0      rẹ̀     NaN
...      ...      ...     ...
1337     NaN      abe     1.0
1338     NaN      two     1.0
1339     NaN    aaaah     1.0
1340     NaN       aa     1.0
1341     NaN  utloisa     1.0

[1342 rows x 3 columns]

In [202]:
pd.merge(df_freq1,df_freq2,on="word",how="left")

     freq_x       word  freq_y
0        86          ó     NaN
1        45         ní     NaN
2        35      ìjàpá     NaN
3        33         ṣe     NaN
4        33        rẹ̀     NaN
..      ...        ...     ...
371       1        aga     NaN
372       1        ọwọ     NaN
373       1  ọ̀pọ̀lọpọ     NaN
374       1      abúlé     NaN
375       1    ọ̀ọ́kán     NaN

[376 rows x 3 columns]

In [203]:
pd.merge(df_freq1,df_freq2,on="word",how="right")

     freq_x     word  freq_y
0       9.0        a     207
1       1.0       le     143
2      16.0        o     110
3       NaN       ba     109
4       NaN       ho     100
..      ...      ...     ...
970     NaN      abe       1
971     NaN      two       1
972     NaN    aaaah       1
973     NaN       aa       1
974     NaN  utloisa       1

[975 rows x 3 columns]

In [204]:
df_freq2

     freq     word
0     207        a
1     143       le
2     110        o
3     109       ba
4     100       ho
..    ...      ...
970     1      abe
971     1      two
972     1    aaaah
973     1       aa
974     1  utloisa

[975 rows x 2 columns]

In [205]:
#pd.merge(df_freq1,df_freq2,left_on="words",right_on="word",how="inner")

###### Concatenating
Attaches dataframes vertically/horizontally

In [206]:
pd.concat([df_freq1,df_freq2],axis=1)

     freq   word  freq     word
0    86.0      ó   207        a
1    45.0     ní   143       le
2    35.0  ìjàpá   110        o
3    33.0     ṣe   109       ba
4    33.0    rẹ̀   100       ho
..    ...    ...   ...      ...
970   NaN    NaN     1      abe
971   NaN    NaN     1      two
972   NaN    NaN     1    aaaah
973   NaN    NaN     1       aa
974   NaN    NaN     1  utloisa

[975 rows x 4 columns]

In [207]:
pd.concat([df_freq1,df_freq2],axis=0)

     freq     word
0      86        ó
1      45       ní
2      35    ìjàpá
3      33       ṣe
4      33      rẹ̀
..    ...      ...
970     1      abe
971     1      two
972     1    aaaah
973     1       aa
974     1  utloisa

[1351 rows x 2 columns]

###### Pivoting
helps restructure the data based on an index <br/>
useful in summarizing data

In [208]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [209]:
df[['Branch','Gender','Unit price']]
#long format

    Branch  Gender  Unit price
0        A  Female       74.69
1        C  Female       15.28
2        A    Male       46.33
3        A    Male       58.22
4        A    Male       86.31
..     ...     ...         ...
995      C    Male       40.35
996      B  Female       97.38
997      A    Male       31.84
998      A    Male       65.82
999      A  Female       88.34

[1000 rows x 3 columns]

In [210]:
df[['Branch','Gender','Unit price']].pivot_table(index='Branch',columns='Gender',values='Unit price',aggfunc='sum')
#wide format

Gender   Female     Male
Branch
A       9029.87  9595.62
B       8775.24  9703.64
C       9882.13  8685.63

In [211]:
#Dropping columns

In [212]:
df=df.drop(['Payment','cogs'],axis=1)

In [213]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,4.761905,30.9190,6.6

### Data Transformation

#### Handle missing data
Note that missing data conventions change from dataset to dataset. <br/>
In some datasets, you will see a fixed value indicating the missing data value. In others, it can be NaN. <br/>
It is important to read the variable descriptions.

In [214]:
df_new= pd.read_csv("datasets/air-quality-monitoring-sites-summary.csv")
df_new=df_new.drop(df_new.columns[0],axis=1)
df_new

,NSW air quality monitoring (AQMN) site,AQMN Region,"Sub-region,where applicable",Site address,Latitude\n(South),Longitude\n(East),Altitude (ahd),Commissioned,Status,PM10,...,NH3,WSP/WD/SD1,TEMP/RH,SOLAR,PRECIPITATION,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,Upper Hunter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulga,Upper Hunter,NaN,1893 Putty Rd,"32°38'56""","151° 2'8""",67.0,2011,Active,ü,...,NaN,ü,ü,NaN,ü,NaN,NaN,NaN,NaN,NaN
2,Camberwell,Upper Hunter,NaN,Dulwich Place and McInerneys Rd,"32°28'20""","151° 5'31""",82.0,2011,Active,ü,...,NaN,ü,ü,NaN,ü,NaN,NaN,NaN,NaN,NaN
3,Maison Dieu,Upper Hunter,NaN,Maison Dieu Rd,"32° 31' 29""","151° 3' 43""",65.0,2011,Active,ü,...,NaN,ü,ü,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mt Thorley,Upper Hunter,NaN,154 Broke Rd,"32°38'9""","151° 7'41""",74.0,2011,Active,ü,...,NaN,ü,ü,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Tibooburra,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,29⁰ 26' 41.28'',142⁰ 3' 24.48'',177.8,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,White Cliffs,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,30⁰ 51' 6.12'',143⁰ 4' 27.12'',159.2,2008,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Coombah,"Rural from ""Rural and regional NSW""",Western LLS,Private property,32⁰ 58' 42.96'',141⁰ 29' 20.4'',193.0,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [215]:
df_new=df_new.dropna(how="all")
df_new

,NSW air quality monitoring (AQMN) site,AQMN Region,"Sub-region,where applicable",Site address,Latitude\n(South),Longitude\n(East),Altitude (ahd),Commissioned,Status,PM10,...,NH3,WSP/WD/SD1,TEMP/RH,SOLAR,PRECIPITATION,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,Upper Hunter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulga,Upper Hunter,NaN,1893 Putty Rd,"32°38'56""","151° 2'8""",67.0,2011,Active,ü,...,NaN,ü,ü,NaN,ü,NaN,NaN,NaN,NaN,NaN
2,Camberwell,Upper Hunter,NaN,Dulwich Place and McInerneys Rd,"32°28'20""","151° 5'31""",82.0,2011,Active,ü,...,NaN,ü,ü,NaN,ü,NaN,NaN,NaN,NaN,NaN
3,Maison Dieu,Upper Hunter,NaN,Maison Dieu Rd,"32° 31' 29""","151° 3' 43""",65.0,2011,Active,ü,...,NaN,ü,ü,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mt Thorley,Upper Hunter,NaN,154 Broke Rd,"32°38'9""","151° 7'41""",74.0,2011,Active,ü,...,NaN,ü,ü,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Lake Victoria,"Rural from ""Rural and regional NSW""",Western LLS,Private property,34⁰ 2' 54.6'',141⁰ 3' 47.88'',54.9,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,Pooncarie,"Rural from ""Rural and regional NSW""",Western LLS,Private property,33⁰ 36' 5.76'',142⁰ 31' 50.88'',323.3,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Tibooburra,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,29⁰ 26' 41.28'',142⁰ 3' 24.48'',177.8,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,White Cliffs,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,30⁰ 51' 6.12'',143⁰ 4' 27.12'',159.2,2008,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Coombah,"Rural from ""Rural and regional NSW""",Western LLS,Private property,32⁰ 58' 42.96'',141⁰ 29' 20.4'',193.0,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [216]:
#helps delete columns that have all Null values
df_new.dropna(axis=1,how='all')

,NSW air quality monitoring (AQMN) site,AQMN Region,"Sub-region,where applicable",Site address,Latitude\n(South),Longitude\n(East),Altitude (ahd),Commissioned,Status,PM10,...,NO/NO2/NOx,SO2,O3,NEPH,CO,NH3,WSP/WD/SD1,TEMP/RH,SOLAR,PRECIPITATION
0,Upper Hunter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulga,Upper Hunter,NaN,1893 Putty Rd,"32°38'56""","151° 2'8""",67.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,ü
2,Camberwell,Upper Hunter,NaN,Dulwich Place and McInerneys Rd,"32°28'20""","151° 5'31""",82.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,ü
3,Maison Dieu,Upper Hunter,NaN,Maison Dieu Rd,"32° 31' 29""","151° 3' 43""",65.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,NaN
4,Mt Thorley,Upper Hunter,NaN,154 Broke Rd,"32°38'9""","151° 7'41""",74.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Lake Victoria,"Rural from ""Rural and regional NSW""",Western LLS,Private property,34⁰ 2' 54.6'',141⁰ 3' 47.88'',54.9,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,Pooncarie,"Rural from ""Rural and regional NSW""",Western LLS,Private property,33⁰ 36' 5.76'',142⁰ 31' 50.88'',323.3,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Tibooburra,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,29⁰ 26' 41.28'',142⁰ 3' 24.48'',177.8,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,White Cliffs,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,30⁰ 51' 6.12'',143⁰ 4' 27.12'',159.2,2008,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Coombah,"Rural from ""Rural and regional NSW""",Western LLS,Private property,32⁰ 58' 42.96'',141⁰ 29' 20.4'',193.0,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [217]:
df_new= df_new.dropna(axis=1,how='all') #for columns
df_new= df_new.dropna(axis=0,how='all') #for rows

In [218]:
df_new

,NSW air quality monitoring (AQMN) site,AQMN Region,"Sub-region,where applicable",Site address,Latitude\n(South),Longitude\n(East),Altitude (ahd),Commissioned,Status,PM10,...,NO/NO2/NOx,SO2,O3,NEPH,CO,NH3,WSP/WD/SD1,TEMP/RH,SOLAR,PRECIPITATION
0,Upper Hunter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulga,Upper Hunter,NaN,1893 Putty Rd,"32°38'56""","151° 2'8""",67.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,ü
2,Camberwell,Upper Hunter,NaN,Dulwich Place and McInerneys Rd,"32°28'20""","151° 5'31""",82.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,ü
3,Maison Dieu,Upper Hunter,NaN,Maison Dieu Rd,"32° 31' 29""","151° 3' 43""",65.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,NaN
4,Mt Thorley,Upper Hunter,NaN,154 Broke Rd,"32°38'9""","151° 7'41""",74.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Lake Victoria,"Rural from ""Rural and regional NSW""",Western LLS,Private property,34⁰ 2' 54.6'',141⁰ 3' 47.88'',54.9,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,Pooncarie,"Rural from ""Rural and regional NSW""",Western LLS,Private property,33⁰ 36' 5.76'',142⁰ 31' 50.88'',323.3,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Tibooburra,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,29⁰ 26' 41.28'',142⁰ 3' 24.48'',177.8,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,White Cliffs,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,30⁰ 51' 6.12'',143⁰ 4' 27.12'',159.2,2008,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Coombah,"Rural from ""Rural and regional NSW""",Western LLS,Private property,32⁰ 58' 42.96'',141⁰ 29' 20.4'',193.0,2004,Active,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [219]:
#fill null values - Data Imputation
df_new.fillna(0)

,NSW air quality monitoring (AQMN) site,AQMN Region,"Sub-region,where applicable",Site address,Latitude\n(South),Longitude\n(East),Altitude (ahd),Commissioned,Status,PM10,...,NO/NO2/NOx,SO2,O3,NEPH,CO,NH3,WSP/WD/SD1,TEMP/RH,SOLAR,PRECIPITATION
0,Upper Hunter,0,0,0,0,0,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Bulga,Upper Hunter,0,1893 Putty Rd,"32°38'56""","151° 2'8""",67.0,2011,Active,ü,...,0,0,0,0,0,0,ü,ü,0,ü
2,Camberwell,Upper Hunter,0,Dulwich Place and McInerneys Rd,"32°28'20""","151° 5'31""",82.0,2011,Active,ü,...,0,0,0,0,0,0,ü,ü,0,ü
3,Maison Dieu,Upper Hunter,0,Maison Dieu Rd,"32° 31' 29""","151° 3' 43""",65.0,2011,Active,ü,...,0,0,0,0,0,0,ü,ü,0,0
4,Mt Thorley,Upper Hunter,0,154 Broke Rd,"32°38'9""","151° 7'41""",74.0,2011,Active,ü,...,0,0,0,0,0,0,ü,ü,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Lake Victoria,"Rural from ""Rural and regional NSW""",Western LLS,Private property,34⁰ 2' 54.6'',141⁰ 3' 47.88'',54.9,2004,Active,0,...,0,0,0,0,0,0,0,0,0,0
96,Pooncarie,"Rural from ""Rural and regional NSW""",Western LLS,Private property,33⁰ 36' 5.76'',142⁰ 31' 50.88'',323.3,2004,Active,0,...,0,0,0,0,0,0,0,0,0,0
97,Tibooburra,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,29⁰ 26' 41.28'',142⁰ 3' 24.48'',177.8,2004,Active,0,...,0,0,0,0,0,0,0,0,0,0
98,White Cliffs,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,30⁰ 51' 6.12'',143⁰ 4' 27.12'',159.2,2008,Active,0,...,0,0,0,0,0,0,0,0,0,0
99,Coombah,"Rural from ""Rural and regional NSW""",Western LLS,Private property,32⁰ 58' 42.96'',141⁰ 29' 20.4'',193.0,2004,Active,0,...,0,0,0,0,0,0,0,0,0,0

In [220]:
df_new.fillna(method='ffill',axis=0)
#makes more sense than the previous one
#useful for time-series data where the previous records are related to the next ones in time

/var/folders/5q/njvzx9bs35sg0dmp71490x800000gn/T/ipykernel_48745/2189803020.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_new.fillna(method='ffill',axis=0)

,NSW air quality monitoring (AQMN) site,AQMN Region,"Sub-region,where applicable",Site address,Latitude\n(South),Longitude\n(East),Altitude (ahd),Commissioned,Status,PM10,...,NO/NO2/NOx,SO2,O3,NEPH,CO,NH3,WSP/WD/SD1,TEMP/RH,SOLAR,PRECIPITATION
0,Upper Hunter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bulga,Upper Hunter,NaN,1893 Putty Rd,"32°38'56""","151° 2'8""",67.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,ü
2,Camberwell,Upper Hunter,NaN,Dulwich Place and McInerneys Rd,"32°28'20""","151° 5'31""",82.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,ü
3,Maison Dieu,Upper Hunter,NaN,Maison Dieu Rd,"32° 31' 29""","151° 3' 43""",65.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,ü
4,Mt Thorley,Upper Hunter,NaN,154 Broke Rd,"32°38'9""","151° 7'41""",74.0,2011,Active,ü,...,NaN,NaN,NaN,NaN,NaN,NaN,ü,ü,NaN,ü
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Lake Victoria,"Rural from ""Rural and regional NSW""",Western LLS,Private property,34⁰ 2' 54.6'',141⁰ 3' 47.88'',54.9,2004,Active,ü,...,ü,ü,ü,ü,ü,ü,ü,ü,ü,ü
96,Pooncarie,"Rural from ""Rural and regional NSW""",Western LLS,Private property,33⁰ 36' 5.76'',142⁰ 31' 50.88'',323.3,2004,Active,ü,...,ü,ü,ü,ü,ü,ü,ü,ü,ü,ü
97,Tibooburra,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,29⁰ 26' 41.28'',142⁰ 3' 24.48'',177.8,2004,Active,ü,...,ü,ü,ü,ü,ü,ü,ü,ü,ü,ü
98,White Cliffs,"Rural from ""Rural and regional NSW""",Western LLS,BoM airport,30⁰ 51' 6.12'',143⁰ 4' 27.12'',159.2,2008,Active,ü,...,ü,ü,ü,ü,ü,ü,ü,ü,ü,ü
99,Coombah,"Rural from ""Rural and regional NSW""",Western LLS,Private property,32⁰ 58' 42.96'',141⁰ 29' 20.4'',193.0,2004,Active,ü,...,ü,ü,ü,ü,ü,ü,ü,ü,ü,ü

In [221]:
df_new['Altitude (ahd)'].fillna(df_new['Altitude (ahd)'].median())
#useful for numerical columns
#median is more robust to outliers than a mean is
#Similarly a mode can be used when you are using categorical data

0     104.7
1      67.0
2      82.0
3      65.0
4      74.0
      ...
95     54.9
96    323.3
97    177.8
98    159.2
99    193.0
Name: Altitude (ahd), Length: 100, dtype: float64

In [222]:
#If you have highly correlated variables, you can use Regression Imputation

In [223]:
#Changing values in original dataframe using a condition
df.loc[df['Unit price'] > 50, 'Unit price'] = 10
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,10.00,7,26.1415,548.9715,1/5/2019,13:08,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,10.00,8,23.2880,489.0480,1/27/2019,20:33,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,10.00,7,30.2085,634.3785,2/8/2019,10:37,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,10.00,10,48.6900,1022.4900,3/2/2019,17:16,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,10.00,1,3.2910,69.1110,2/22/2019,15:33,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,10.00,7,30.9190,649.2990,2/18/2019,13:28,4.761905,30.9190,6.6

In [224]:
df[['Branch','Gender']]

    Branch  Gender
0        A  Female
1        C  Female
2        A    Male
3        A    Male
4        A    Male
..     ...     ...
995      C    Male
996      B  Female
997      A    Male
998      A    Male
999      A  Female

[1000 rows x 2 columns]

In [225]:
df[['Branch','Gender']].duplicated()

0      False
1      False
2      False
3       True
4       True
       ...
995     True
996     True
997     True
998     True
999     True
Length: 1000, dtype: bool

In [226]:
#Drop duplicates

In [227]:

df[~(df[['Branch','Gender']].duplicated())][['Branch','Gender']]

   Branch  Gender
0       A  Female
1       C  Female
2       A    Male
5       C    Male
9       B  Female
11      B    Male

In [228]:
df[['Branch','Gender']].drop_duplicates()

   Branch  Gender
0       A  Female
1       C  Female
2       A    Male
5       C    Male
9       B  Female
11      B    Male

In [229]:
#Mapping

In [230]:
map = {'A':30,'B':40,'C':50}
map

{'A': 30, 'B': 40, 'C': 50}

In [231]:
df['Branch']

0      A
1      C
2      A
3      A
4      A
      ..
995    C
996    B
997    A
998    A
999    A
Name: Branch, Length: 1000, dtype: object

In [232]:
df.replace(map)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,gross margin percentage,gross income,Rating
0,750-67-8428,30,Yangon,Member,Female,Health and beauty,10.00,7,26.1415,548.9715,1/5/2019,13:08,4.761905,26.1415,9.1
1,226-31-3081,50,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,4.761905,3.8200,9.6
2,631-41-3108,30,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,4.761905,16.2155,7.4
3,123-19-1176,30,Yangon,Member,Male,Health and beauty,10.00,8,23.2880,489.0480,1/27/2019,20:33,4.761905,23.2880,8.4
4,373-73-7910,30,Yangon,Normal,Male,Sports and travel,10.00,7,30.2085,634.3785,2/8/2019,10:37,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,50,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,4.761905,2.0175,6.2
996,303-96-2227,40,Mandalay,Normal,Female,Home and lifestyle,10.00,10,48.6900,1022.4900,3/2/2019,17:16,4.761905,48.6900,4.4
997,727-02-1313,30,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,4.761905,1.5920,7.7
998,347-56-2442,30,Yangon,Normal,Male,Home and lifestyle,10.00,1,3.2910,69.1110,2/22/2019,15:33,4.761905,3.2910,4.1
999,849-09-3807,30,Yangon,Member,Female,Fashion accessories,10.00,7,30.9190,649.2990,2/18/2019,13:28,4.761905,30.9190,6.6

In [233]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,10.00,7,26.1415,548.9715,1/5/2019,13:08,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,10.00,8,23.2880,489.0480,1/27/2019,20:33,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,10.00,7,30.2085,634.3785,2/8/2019,10:37,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,10.00,10,48.6900,1022.4900,3/2/2019,17:16,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,10.00,1,3.2910,69.1110,2/22/2019,15:33,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,10.00,7,30.9190,649.2990,2/18/2019,13:28,4.761905,30.9190,6.6

In [234]:
salaries = {'A': 30, 'B': 40, 'C': 50}

In [235]:
df['sal'] = df['Branch'].map(salaries)

In [236]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,gross margin percentage,gross income,Rating,sal
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,10.00,7,26.1415,548.9715,1/5/2019,13:08,4.761905,26.1415,9.1,30
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,4.761905,3.8200,9.6,50
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,4.761905,16.2155,7.4,30
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,10.00,8,23.2880,489.0480,1/27/2019,20:33,4.761905,23.2880,8.4,30
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,10.00,7,30.2085,634.3785,2/8/2019,10:37,4.761905,30.2085,5.3,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,4.761905,2.0175,6.2,50
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,10.00,10,48.6900,1022.4900,3/2/2019,17:16,4.761905,48.6900,4.4,40
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,4.761905,1.5920,7.7,30
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,10.00,1,3.2910,69.1110,2/22/2019,15:33,4.761905,3.2910,4.1,30
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,10.00,7,30.9190,649.2990,2/18/2019,13:28,4.761905,30.9190,6.6,30

In [237]:
df[['sal','Branch']]

     sal Branch
0     30      A
1     50      C
2     30      A
3     30      A
4     30      A
..   ...    ...
995   50      C
996   40      B
997   30      A
998   30      A
999   30      A

[1000 rows x 2 columns]

### Discretization and Binning <br/>
helps with simplifying data, help understand relationships in data much better and interpretable

In [238]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,gross margin percentage,gross income,Rating,sal
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,10.00,7,26.1415,548.9715,1/5/2019,13:08,4.761905,26.1415,9.1,30
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,4.761905,3.8200,9.6,50
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,4.761905,16.2155,7.4,30
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,10.00,8,23.2880,489.0480,1/27/2019,20:33,4.761905,23.2880,8.4,30
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,10.00,7,30.2085,634.3785,2/8/2019,10:37,4.761905,30.2085,5.3,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,4.761905,2.0175,6.2,50
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,10.00,10,48.6900,1022.4900,3/2/2019,17:16,4.761905,48.6900,4.4,40
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,4.761905,1.5920,7.7,30
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,10.00,1,3.2910,69.1110,2/22/2019,15:33,4.761905,3.2910,4.1,30
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,10.00,7,30.9190,649.2990,2/18/2019,13:28,4.761905,30.9190,6.6,30

In [239]:
df['Unit price'].describe()

count    1000.000000
mean       18.745200
std        12.482444
min        10.000000
25%        10.000000
50%        10.000000
75%        26.272500
max        49.920000
Name: Unit price, dtype: float64

In [240]:
bins = [0,10,20,30,40,50]
pd.cut(df['Unit price'], bins)

0       (0, 10]
1      (10, 20]
2      (40, 50]
3       (0, 10]
4       (0, 10]
         ...
995    (40, 50]
996     (0, 10]
997    (30, 40]
998     (0, 10]
999     (0, 10]
Name: Unit price, Length: 1000, dtype: category
Categories (5, interval[int64, right]): [(0, 10] < (10, 20] < (20, 30] < (30, 40] < (40, 50]]

In [241]:
df['price_disc'] = pd.cut(df['Unit price'], bins) #Create new column for bins
df['price_disc'].value_counts() #gives a frequency count of each category

price_disc
(0, 10]     561
(20, 30]    118
(30, 40]    108
(40, 50]    107
(10, 20]    106
Name: count, dtype: int64

In [242]:
#you can also rename these values
bin_names = ['very low', 'low', 'medium', 'high', 'very high']
df['cat_price_disc'] = pd.cut(df['Unit price'], bins, labels=bin_names)
df['cat_price_disc']

0       very low
1            low
2      very high
3       very low
4       very low
         ...
995    very high
996     very low
997         high
998     very low
999     very low
Name: cat_price_disc, Length: 1000, dtype: category
Categories (5, object): ['very low' < 'low' < 'medium' < 'high' < 'very high']

In [243]:
#you can also split into 'n' different bins
#notice how the bins are split in this case
pd.cut(df['Unit price'], 5)

0        (9.96, 17.984]
1        (9.96, 17.984]
2       (41.936, 49.92]
3        (9.96, 17.984]
4        (9.96, 17.984]
             ...
995    (33.952, 41.936]
996      (9.96, 17.984]
997    (25.968, 33.952]
998      (9.96, 17.984]
999      (9.96, 17.984]
Name: Unit price, Length: 1000, dtype: category
Categories (5, interval[float64, right]): [(9.96, 17.984] < (17.984, 25.968] < (25.968, 33.952] < (33.952, 41.936] < (41.936, 49.92]]

In [244]:
pd.cut(df['Unit price'],5).value_counts()

Unit price
(9.96, 17.984]      647
(17.984, 25.968]     99
(33.952, 41.936]     88
(41.936, 49.92]      88
(25.968, 33.952]     78
Name: count, dtype: int64

In [245]:
# Quantile Cut
# There cannot be duplicates with qcut. Look at describe(), 10 repeats.
pd.qcut(df['Unit price'], 4)

ValueError: Bin edges must be unique: array([10.    , 10.    , 10.    , 26.2725, 49.92  ]).
You can drop duplicate edges by setting the 'duplicates' kwarg

In [ ]:
# We can drop duplicates when doing a quantile cut
pd.qcut(df['Unit price'], 4, duplicates='drop')

0      (9.999, 26.272]
1      (9.999, 26.272]
2      (26.272, 49.92]
3      (9.999, 26.272]
4      (9.999, 26.272]
            ...
995    (26.272, 49.92]
996    (9.999, 26.272]
997    (26.272, 49.92]
998    (9.999, 26.272]
999    (9.999, 26.272]
Name: Unit price, Length: 1000, dtype: category
Categories (2, interval[float64, right]): [(9.999, 26.272] < (26.272, 49.92]]

In [ ]:
df['Total_q'] = pd.qcut(df['Total'],4)
df['Total_q']

0                  (471.35, 1042.65]
1      (10.677000000000001, 124.422]
2                  (253.848, 471.35]
3                  (471.35, 1042.65]
4                  (471.35, 1042.65]
                   ...
995    (10.677000000000001, 124.422]
996                (471.35, 1042.65]
997    (10.677000000000001, 124.422]
998    (10.677000000000001, 124.422]
999                (471.35, 1042.65]
Name: Total_q, Length: 1000, dtype: category
Categories (4, interval[float64, right]): [(10.677000000000001, 124.422] < (124.422, 253.848] < (253.848, 471.35] < (471.35, 1042.65]]

In [ ]:
# Notice how the value counts are equal for each bin.
df['Total_q'].value_counts()

Total_q
(10.677000000000001, 124.422]    250
(124.422, 253.848]               250
(253.848, 471.35]                250
(471.35, 1042.65]                250
Name: count, dtype: int64

### Detecting and Filtering Outliers

In [ ]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'gross margin percentage', 'gross income', 'Rating', 'sal',
       'price_disc', 'cat_price_disc', 'Total_q'],
      dtype='object')

In [ ]:
df[['Unit price','Quantity','Tax 5%','Total','gross margin percentage','gross income','Rating']].std()

Unit price                 1.248244e+01
Quantity                   2.923431e+00
Tax 5%                     1.170883e+01
Total                      2.458853e+02
gross margin percentage    6.131498e-14
gross income               1.170883e+01
Rating                     1.718580e+00
dtype: float64

In [ ]:
df_new = df[['Unit price','Quantity','Tax 5%','Total','gross income','Rating']]

In [ ]:
df_new

     Unit price  Quantity   Tax 5%      Total  gross income  Rating
0         10.00         7  26.1415   548.9715       26.1415     9.1
1         15.28         5   3.8200    80.2200        3.8200     9.6
2         46.33         7  16.2155   340.5255       16.2155     7.4
3         10.00         8  23.2880   489.0480       23.2880     8.4
4         10.00         7  30.2085   634.3785       30.2085     5.3
..          ...       ...      ...        ...           ...     ...
995       40.35         1   2.0175    42.3675        2.0175     6.2
996       10.00       100  48.6900  1022.4900       48.6900     4.4
997       31.84         1   1.5920    33.4320        1.5920     7.7
998       10.00         1   3.2910    69.1110        3.2910     4.1
999       10.00         7  30.9190   649.2990       30.9190     6.6

[1000 rows x 6 columns]

In [ ]:
df_new['Quantity'][996] = 100
df_new['Quantity'][986] = 100
df_new['Quantity'][946] = 100

/var/folders/5q/njvzx9bs35sg0dmp71490x800000gn/T/ipykernel_48745/2714786813.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Quantity'][996] = 100
/var/folders/5q/njvzx9bs35sg0dmp71490x800000gn/T/ipykernel_48745/2714786813.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Quantity'][986] = 100
/var/folders/5q/njvzx9bs35sg0dmp71490x800000gn/T/ipykernel_48745/2714786813.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['Quantity'][946] = 100

In [ ]:
mean = df_new['Quantity'].mean()
std = df_new['Quantity'].std()
outliers = df_new[(df_new['Quantity'] - mean).abs() > 3 * std]

In [ ]:
outliers

     Unit price  Quantity  Tax 5%     Total  gross income  Rating
946       10.00       100   8.425   176.925         8.425     5.3
986       14.76       100   1.476    30.996         1.476     4.3
996       10.00       100  48.690  1022.490        48.690     4.4

In [ ]:
#how to repeat it for all the columns
for col in df_new:
    mean = df_new[col].mean()
    std = df_new[col].std()
    outliers = df_new[(df_new[col] - mean).abs() > 3 * std]
    print(outliers)

Empty DataFrame
Columns: [Unit price, Quantity, Tax 5%, Total, gross income, Rating]
Index: []
     Unit price  Quantity  Tax 5%     Total  gross income  Rating
946       10.00       100   8.425   176.925         8.425     5.3
986       14.76       100   1.476    30.996         1.476     4.3
996       10.00       100  48.690  1022.490        48.690     4.4
Empty DataFrame
Columns: [Unit price, Quantity, Tax 5%, Total, gross income, Rating]
Index: []
Empty DataFrame
Columns: [Unit price, Quantity, Tax 5%, Total, gross income, Rating]
Index: []
Empty DataFrame
Columns: [Unit price, Quantity, Tax 5%, Total, gross income, Rating]
Index: []
Empty DataFrame
Columns: [Unit price, Quantity, Tax 5%, Total, gross income, Rating]
Index: []

In [ ]:
# Using a for loop to see value counts of all columns in df.
for col in df:
    print(df[col].value_counts())

Invoice ID
750-67-8428    1
642-61-4706    1
816-72-8853    1
491-38-3499    1
322-02-2271    1
              ..
633-09-3463    1
374-17-3652    1
378-07-7001    1
433-75-6987    1
849-09-3807    1
Name: count, Length: 1000, dtype: int64
Branch
A    340
B    332
C    328
Name: count, dtype: int64
City
Yangon       340
Mandalay     332
Naypyitaw    328
Name: count, dtype: int64
Customer type
Member    501
Normal    499
Name: count, dtype: int64
Gender
Female    501
Male      499
Name: count, dtype: int64
Product line
Fashion accessories       178
Food and beverages        174
Electronic accessories    170
Sports and travel         166
Home and lifestyle        160
Health and beauty         152
Name: count, dtype: int64
Unit price
10.00    561
48.50      2
24.74      2
38.60      2
45.38      2
        ...
22.02      1
21.52      1
15.26      1
39.42      1
31.84      1
Name: count, Length: 412, dtype: int64
Quantity
10    119
1     112
4     109
7     102
5     102
6      98
9      92
2      91
3      90
8      85
Name: count, dtype: int64
Tax 5%
10.3260    2
4.4640     2
4.1540     2
9.0045     2
22.4280    2
          ..
7.2135     1
19.5895    1
26.9150    1
24.2575    1
30.9190    1
Name: count, Length: 990, dtype: int64
Total
216.8460    2
93.7440     2
87.2340     2
189.0945    2
470.9880    2
           ..
151.4835    1
411.3795    1
565.2150    1
509.4075    1
649.2990    1
Name: count, Length: 990, dtype: int64
Date
2/7/2019     20
2/15/2019    19
3/14/2019    18
3/2/2019     18
1/8/2019     18
             ..
1/4/2019      6
2/28/2019     6
2/21/2019     6
3/17/2019     6
2/1/2019      6
Name: count, Length: 89, dtype: int64
Time
19:48    7
14:42    7
17:38    6
17:16    5
11:40    5
        ..
13:26    1
11:17    1
14:57    1
17:53    1
19:12    1
Name: count, Length: 506, dtype: int64
gross margin percentage
4.761905    1000
Name: count, dtype: int64
gross income
10.3260    2
4.4640     2
4.1540     2
9.0045     2
22.4280    2
          ..
7.2135     1
19.5895    1
26.9150    1
24.2575    1
30.9190    1
Name: count, Length: 990, dtype: int64
Rating
6.0     26
6.6     24
4.2     22
9.5     22
6.5     21
        ..
4.0     11
5.3     11
8.3     11
4.6      8
10.0     5
Name: count, Length: 61, dtype: int64
sal
30    340
40    332
50    328
Name: count, dtype: int64
price_disc
(0, 10]     561
(20, 30]    118
(30, 40]    108
(40, 50]    107
(10, 20]    106
Name: count, dtype: int64
cat_price_disc
very low     561
medium       118
high         108
very high    107
low          106
Name: count, dtype: int64
Total_q
(10.677000000000001, 124.422]    250
(124.422, 253.848]               250
(253.848, 471.35]                250
(471.35, 1042.65]                250
Name: count, dtype: int64

### Permutation and Random Sampling

In [ ]:
import numpy as np
np.random.permutation(5)

array([4, 1, 0, 2, 3])

In [ ]:
l1 = np.random.permutation(5)
df_new.take(l1)

   Unit price  Quantity   Tax 5%     Total  gross income  Rating
0       10.00         7  26.1415  548.9715       26.1415     9.1
2       46.33         7  16.2155  340.5255       16.2155     7.4
1       15.28         5   3.8200   80.2200        3.8200     9.6
4       10.00         7  30.2085  634.3785       30.2085     5.3
3       10.00         8  23.2880  489.0480       23.2880     8.4

In [ ]:
len(df_new)

1000

In [ ]:
np.random.randint(0,len(df_new), size = 100)

array([185, 500, 984, 187, 979, 670, 136, 470, 668, 748,  81, 167, 130,
       730, 894, 437, 937, 411, 945, 383, 754, 226, 973, 417,  26, 852,
       341, 491, 700, 487, 414, 804, 941, 223, 590, 437, 872,  97, 926,
        21, 866, 783, 872, 804, 393, 843, 606, 804, 108,   4, 683,  55,
       423, 401, 855, 174, 246, 438, 230, 964, 757, 128, 855, 480, 639,
       970, 794, 157, 793, 575, 794, 672, 655, 796,  63,   2, 944, 211,
       109, 603,  95,  73, 185, 157,  64, 210, 427, 533, 978, 459, 103,
       184, 589, 762, 354, 252, 356, 203, 609, 371])

In [ ]:
l1 = np.random.randint(0,len(df_new), size = 100)

In [ ]:
df_new.take(l1)

     Unit price  Quantity   Tax 5%     Total  gross income  Rating
819       47.16         5  11.7900  247.5900       11.7900     6.0
51        44.59         5  11.1475  234.0975       11.1475     8.5
362       10.00         2   9.9790  209.5590        9.9790     8.0
614       10.00        10  33.7250  708.2250       33.7250     4.2
41        10.00         2   5.6110  117.8310        5.6110     6.3
..          ...       ...      ...       ...           ...     ...
442       10.00         9  40.1445  843.0345       40.1445     6.5
858       10.00         6  17.2770  362.8170       17.2770     5.1
805       10.00         4  15.4940  325.3740       15.4940     4.2
970       10.00        10  42.3150  888.6150       42.3150     9.0
263       22.24        10  11.1200  233.5200       11.1200     4.2

[100 rows x 6 columns]

### String Manipulations

In [ ]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,gross margin percentage,gross income,Rating,sal,price_disc,cat_price_disc,Total_q
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,10.00,7,26.1415,548.9715,1/5/2019,13:08,4.761905,26.1415,9.1,30,"(0, 10]",very low,"(471.35, 1042.65]"
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,4.761905,3.8200,9.6,50,"(10, 20]",low,"(10.677000000000001, 124.422]"
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,4.761905,16.2155,7.4,30,"(40, 50]",very high,"(253.848, 471.35]"
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,10.00,8,23.2880,489.0480,1/27/2019,20:33,4.761905,23.2880,8.4,30,"(0, 10]",very low,"(471.35, 1042.65]"
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,10.00,7,30.2085,634.3785,2/8/2019,10:37,4.761905,30.2085,5.3,30,"(0, 10]",very low,"(471.35, 1042.65]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,4.761905,2.0175,6.2,50,"(40, 50]",very high,"(10.677000000000001, 124.422]"
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,10.00,10,48.6900,1022.4900,3/2/2019,17:16,4.761905,48.6900,4.4,40,"(0, 10]",very low,"(471.35, 1042.65]"
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,4.761905,1.5920,7.7,30,"(30, 40]",high,"(10.677000000000001, 124.422]"
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,10.00,1,3.2910,69.1110,2/22/2019,15:33,4.761905,3.2910,4.1,30,"(0, 10]",very low,"(10.677000000000001, 124.422]"
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,10.00,7,30.9190,649.2990,2/18/2019,13:28,4.761905,30.9190,6.6,30,"(0, 10]",very low,"(471.35, 1042.65]"

In [ ]:
df.iloc[0,0]

'750-67-8428'

In [ ]:
import re
#re is used for pattern matching, splitting and substitution
re.split('-',df.iloc[0,0])

['750', '67', '8428']

In [ ]:
#split a string based on a character
l2 = [re.split('-',x) for x in df['Invoice ID']]
l2

[['750', '67', '8428'],
 ['226', '31', '3081'],
 ['631', '41', '3108'],
 ['123', '19', '1176'],
 ['373', '73', '7910'],
 ['699', '14', '3026'],
 ['355', '53', '5943'],
 ['315', '22', '5665'],
 ['665', '32', '9167'],
 ['692', '92', '5582'],
 ['351', '62', '0822'],
 ['529', '56', '3974'],
 ['365', '64', '0515'],
 ['252', '56', '2699'],
 ['829', '34', '3910'],
 ['299', '46', '1805'],
 ['656', '95', '9349'],
 ['765', '26', '6951'],
 ['329', '62', '1586'],
 ['319', '50', '3348'],
 ['300', '71', '4605'],
 ['371', '85', '5789'],
 ['273', '16', '6619'],
 ['636', '48', '8204'],
 ['549', '59', '1358'],
 ['227', '03', '5010'],
 ['649', '29', '6775'],
 ['189', '17', '4241'],
 ['145', '94', '9061'],
 ['848', '62', '7243'],
 ['871', '79', '8483'],
 ['149', '71', '6266'],
 ['640', '49', '2076'],
 ['595', '11', '5460'],
 ['183', '56', '6882'],
 ['232', '16', '2483'],
 ['129', '29', '8530'],
 ['272', '65', '1806'],
 ['333', '73', '7901'],
 ['777', '82', '7220'],
 ['280', '35', '5823'],
 ['554', '53', '8700'],
 ['354', '25', '5821'],
 ['228', '96', '1411'],
 ['617', '15', '4209'],
 ['132', '32', '9879'],
 ['370', '41', '7321'],
 ['727', '46', '3608'],
 ['669', '54', '1719'],
 ['574', '22', '5561'],
 ['326', '78', '5178'],
 ['162', '48', '8011'],
 ['616', '24', '2851'],
 ['778', '71', '5554'],
 ['242', '55', '6721'],
 ['399', '46', '5918'],
 ['106', '35', '6779'],
 ['635', '40', '6220'],
 ['817', '48', '8732'],
 ['120', '06', '4233'],
 ['285', '68', '5083'],
 ['803', '83', '5989'],
 ['347', '34', '2234'],
 ['199', '75', '8169'],
 ['853', '23', '2453'],
 ['877', '22', '3308'],
 ['838', '78', '4295'],
 ['109', '28', '2512'],
 ['232', '11', '3025'],
 ['382', '03', '4532'],
 ['393', '65', '2792'],
 ['796', '12', '2025'],
 ['510', '95', '6347'],
 ['841', '35', '6630'],
 ['287', '21', '9091'],
 ['732', '94', '0499'],
 ['263', '10', '3913'],
 ['381', '20', '0914'],
 ['829', '49', '1914'],
 ['756', '01', '7507'],
 ['870', '72', '4431'],
 ['847', '38', '7188'],
 ['480', '63', '2856'],
 ['787', '56', '0757'],
 ['360', '39', '5055'],
 ['730', '50', '9884'],
 ['362', '58', '8315'],
 ['633', '44', '8566'],
 ['504', '35', '8843'],
 ['318', '68', '5053'],
 ['565', '80', '5980'],
 ['225', '32', '0908'],
 ['873', '51', '0671'],
 ['152', '08', '9985'],
 ['512', '91', '0811'],
 ['594', '34', '4444'],
 ['766', '85', '7061'],
 ['871', '39', '9221'],
 ['865', '92', '6136'],
 ['733', '01', '9107'],
 ['163', '56', '7055'],
 ['189', '98', '2939'],
 ['551', '21', '3069'],
 ['212', '62', '1842'],
 ['716', '39', '1409'],
 ['704', '48', '3927'],
 ['628', '34', '3388'],
 ['630', '74', '5166'],
 ['588', '01', '7461'],
 ['861', '77', '0145'],
 ['479', '26', '8945'],
 ['210', '67', '5886'],
 ['227', '78', '1148'],
 ['645', '44', '1170'],
 ['237', '01', '6122'],
 ['225', '98', '1496'],
 ['291', '32', '1427'],
 ['659', '65', '8956'],
 ['642', '32', '2990'],
 ['378', '24', '2715'],
 ['638', '60', '7125'],
 ['659', '36', '1684'],
 ['219', '22', '9386'],
 ['336', '78', '2147'],
 ['268', '27', '6179'],
 ['668', '90', '8900'],
 ['870', '54', '3162'],
 ['189', '08', '9157'],
 ['663', '86', '9076'],
 ['549', '84', '7482'],
 ['191', '10', '6171'],
 ['802', '70', '5316'],
 ['695', '51', '0018'],
 ['590', '83', '4591'],
 ['483', '71', '1164'],
 ['597', '78', '7908'],
 ['700', '81', '1757'],
 ['354', '39', '5160'],
 ['241', '72', '9525'],
 ['575', '30', '8091'],
 ['731', '81', '9469'],
 ['280', '17', '4359'],
 ['338', '65', '2210'],
 ['488', '25', '4221'],
 ['239', '10', '7476'],
 ['458', '41', '1477'],
 ['685', '64', '1609'],
 ['568', '90', '5112'],
 ['262', '47', '2794'],
 ['238', '49', '0436'],
 ['608', '96', '3517'],
 ['584', '86', '7256'],
 ['746', '94', '0204'],
 ['214', '17', '6927'],
 ['400', '89', '4171'],
 ['782', '95', '9291'],
 ['279', '74', '2924'],
 ['307', '85', '2293'],
 ['743', '04', '1105'],
 ['423', '57', '2993'],
 ['894', '41', '5205'],
 ['275', '28', '0149'],
 ['101', '17', '6199'],
 ['423', '80', '0988'],
 ['548', '46', '9322'],
 ['505', '02', '0892'],
 ['234', '65', '2137'],
 ['687', '47', '8271'],
 ['796', '32', '9050'],
 ['105', '31', '1824'],
 ['249', '42', '3782'],
 ['316', '55', '4634'],
 ['733', '33', '4967'],
 ['608', '27', '6295'],
 ['414', '12', '7047'],
 ['827', '26', '2100'],
 ['175', '54', '2529'],
 ['139', '52', '2867'],
 ['407', '63', '8975'],
 ['342', '65', '4817'],
 ['130', '98', '8941'],
 ['434', '83', '9547'],
 ['851', '28', '6367'],
 ['824', '88', '3614'],
 ['586', '25', '0848'],
 ['895', '66', '0685'],
 ['305', '14', '0245'],
 ['732', '04', '5373'],
 ['400', '60', '7251'],
 ['593', '65', '1552'],
 ['284', '34', '9626'],
 ['437', '58', '8131'],
 ['286', '43', '6208'],
 ['641', '43', '2399'],
 ['831', '07', '6050'],
 ['556', '86', '3144'],
 ['848', '24', '9445'],
 ['856', '22', '8149'],
 ['699', '01', '4164'],
 ['420', '11', '4919'],
 ['606', '80', '4905'],
 ['542', '41', '0513'],
 ['426', '39', '2418'],
 ['875', '46', '5808'],
 ['394', '43', '4238'],
 ['749', '24', '1565'],
 ['672', '51', '8681'],
 ['263', '87', '5680'],
 ['573', '58', '9734'],
 ['817', '69', '8206'],
 ['888', '02', '0338'],
 ['677', '11', '0152'],
 ['142', '63', '6033'],
 ['656', '16', '1063'],
 ['891', '58', '8335'],
 ['802', '43', '8934'],
 ['560', '30', '5617'],
 ['319', '74', '2561'],
 ['549', '03', '9315'],
 ['790', '29', '1172'],
 ['239', '36', '3640'],
 ['468', '01', '2051'],
 ['389', '25', '3394'],
 ['279', '62', '1445'],
 ['213', '72', '6612'],
 ['746', '68', '6593'],
 ['836', '82', '5858'],
 ['583', '72', '1480'],
 ['466', '61', '5506'],
 ['721', '86', '6247'],
 ['289', '65', '5721'],
 ['545', '46', '3100'],
 ['418', '02', '5978'],
 ['269', '04', '5750'],
 ['157', '13', '5295'],
 ['645', '78', '8093'],
 ['211', '30', '9270'],
 ['755', '12', '3214'],
 ['346', '84', '3103'],
 ['478', '06', '7835'],
 ['540', '11', '4336'],
 ['448', '81', '5016'],
 ['142', '72', '4741'],
 ['217', '58', '1179'],
 ['376', '02', '8238'],
 ['530', '90', '9855'],
 ['866', '05', '7563'],
 ['604', '70', '6476'],
 ['799', '71', '1548'],
 ['785', '13', '7708'],
 ['845', '51', '0542'],
 ['662', '47', '5456'],
 ['883', '17', '4236'],
 ['290', '68', '2984'],
 ['704', '11', '6354'],
 ['110', '48', '7033'],
 ['366', '93', '0948'],
 ['729', '09', '9681'],
 ['151', '16', '1484'],
 ['380', '94', '4661'],
 ['850', '41', '9669'],
 ['821', '07', '3596'],
 ['655', '85', '5130'],
 ['447', '15', '7839'],
 ['154', '74', '7179'],
 ['253', '12', '6086'],
 ['808', '65', '0703'],
 ['571', '94', '0759'],
 ['144', '51', '6085'],
 ['731', '14', '2199'],
 ['783', '09', '1637'],
 ['687', '15', '1097'],
 ['126', '54', '1082'],
 ['633', '91', '1052'],
 ['477', '24', '6490'],
 ['566', '19', '5475'],
 ['526', '86', '8552'],
 ['376', '56', '3573'],
 ['537', '72', '0426'],
 ['828', '61', '5674'],
 ['136', '08', '6195'],
 ['523', '38', '0215'],
 ['490', '29', '1201'],
 ['667', '92', '0055'],
 ['565', '17', '3836'],
 ['498', '41', '1961'],
 ['593', '95', '4461'],
 ['226', '71', '3580'],
 ['283', '79', '9594'],
 ['430', '60', '3493'],
 ['139', '20', '0155'],
 ['558', '80', '4082'],
 ['278', '97', '7759'],
 ['316', '68', '6352'],
 ['585', '03', '5943'],
 ['211', '05', '0490'],
 ['727', '75', '6477'],
 ['744', '02', '5987'],
 ['307', '83', '9164'],
 ['779', '06', '0012'],
 ['446', '47', '6729'],
 ['573', '10', '3877'],
 ['735', '06', '4124'],
 ['439', '54', '7422'],
 ['396', '90', '2219'],
 ['411', '77', '0180'],
 ['286', '01', '5402'],
 ['803', '17', '8013'],
 ['512', '98', '1403'],
 ['848', '42', '2560'],
 ['532', '59', '7201'],
 ['181', '94', '6432'],
 ['870', '76', '1733'],
 ['423', '64', '4619'],
 ['227', '07', '4446'],
 ['174', '36', '3675'],
 ['428', '83', '5800'],
 ['603', '07', '0961'],
 ['704', '20', '4138'],
 ['787', '15', '1757'],
 ['649', '11', '3678'],
 ['622', '20', '1945'],
 ['372', '94', '8041'],
 ['563', '91', '7120'],
 ['746', '54', '5508'],
 ['276', '54', '0879'],
 ['815', '11', '1168'],
 ['719', '76', '3868'],
 ['730', '61', '8757'],
 ['340', '66', '0321'],
 ['868', '81', '1752'],
 ['634', '97', '8956'],
 ['566', '71', '1091'],
 ['442', '48', '3607'],
 ['835', '16', '0096'],
 ['527', '09', '6272'],
 ['898', '04', '2717'],
 ['692', '27', '8933'],
 ['633', '09', '3463'],
 ['374', '17', '3652'],
 ['378', '07', '7001'],
 ['433', '75', '6987'],
 ['873', '95', '4984'],
 ['416', '13', '5917'],
 ['150', '89', '8043'],
 ['135', '84', '8019'],
 ['441', '94', '7118'],
 ['725', '96', '3778'],
 ['531', '80', '1784'],
 ['400', '45', '1220'],
 ['860', '79', '0874'],
 ['834', '61', '8124'],
 ['115', '99', '4379'],
 ['565', '67', '6697'],
 ['320', '49', '6392'],
 ['889', '04', '9723'],
 ['632', '90', '0281'],
 ['554', '42', '2417'],
 ['453', '63', '6187'],
 ['578', '80', '7669'],
 ['612', '36', '5536'],
 ['605', '72', '4132'],
 ['471', '41', '2823'],
 ['462', '67', '9126'],
 ['272', '27', '9238'],
 ['834', '25', '9262'],
 ['122', '61', '9553'],
 ['468', '88', '0009'],
 ['613', '59', '9758'],
 ['254', '31', '0042'],
 ['201', '86', '2184'],
 ['261', '12', '8671'],
 ['730', '70', '9830'],
 ['382', '25', '8917'],
 ['422', '29', '8786'],
 ['667', '23', '5919'],
 ['843', '01', '4703'],
 ['743', '88', '1662'],
 ['595', '86', '2894'],
 ['182', '69', '8360'],
 ['289', '15', '7034'],
 ['462', '78', '5240'],
 ['868', '52', '7573'],
 ['153', '58', '4872'],
 ['662', '72', '2873'],
 ['525', '88', '7307'],
 ['689', '16', '9784'],
 ['725', '56', '0833'],
 ['394', '41', '0748'],
 ['596', '42', '3999'],
 ['541', '89', '9860'],
 ['173', '82', '9529'],
 ['563', '36', '9814'],
 ['308', '47', '4913'],
 ['885', '17', '6250'],
 ['726', '27', '2396'],
 ['316', '01', '3952'],
 ['760', '54', '1821'],
 ['793', '10', '3222'],
 ['346', '12', '3257'],
 ['110', '05', '6330'],
 ['651', '61', '0874'],
 ['236', '86', '3015'],
 ['831', '64', '0259'],
 ['587', '03', '7455'],
 ['882', '40', '4577'],
 ['732', '67', '5346'],
 ['725', '32', '9708'],
 ['256', '08', '8343'],
 ['372', '26', '1506'],
 ['244', '08', '0162'],
 ['569', '71', '4390'],
 ['132', '23', '6451'],
 ['696', '90', '2548'],
 ['472', '15', '9636'],
 ['268', '03', '6164'],
 ['750', '57', '9686'],
 ['186', '09', '3669'],
 ['848', '07', '1692'],
 ['745', '71', '3520'],
 ['266', '76', '6436'],
 ['740', '22', '2500'],
 ['271', '88', '8734'],
 ['301', '81', '8610'],
 ['489', '64', '4354'],
 ['198', '84', '7132'],
 ['269', '10', '8440'],
 ['650', '98', '6268'],
 ['741', '73', '3559'],
 ['325', '77', '6186'],
 ['286', '75', '7818'],
 ['574', '57', '9721'],
 ['459', '50', '7686'],
 ['616', '87', '0016'],
 ['837', '55', '7229'],
 ['751', '69', '0068'],
 ['257', '73', '1380'],
 ['345', '08', '4992'],
 ['549', '96', '4200'],
 ['810', '60', '6344'],
 ['450', '28', '2866'],
 ['394', '30', '3170'],
 ['138', '17', '5109'],
 ['192', '98', '7397'],
 ['301', '11', '9629'],
 ['390', '80', '5128'],
 ['235', '46', '8343'],
 ['453', '12', '7053'],
 ['296', '11', '7041'],
 ['449', '27', '2918'],
 ['891', '01', '7034'],
 ['744', '09', '5786'],
 ['727', '17', '0390'],
 ['568', '88', '3448'],
 ['187', '83', '5490'],
 ['767', '54', '1907'],
 ['710', '46', '4433'],
 ['533', '33', '5337'],
 ['325', '90', '8763'],
 ['729', '46', '7422'],
 ['639', '76', '1242'],
 ['234', '03', '4040'],
 ['326', '71', '2155'],
 ['320', '32', '8842'],
 ['470', '32', '9057'],
 ['878', '30', '2331'],
 ['440', '59', '5691'],
 ['554', '53', '3790'],
 ['746', '19', '0921'],
 ['233', '34', '0817'],
 ['767', '05', '1286'],
 ['340', '21', '9136'],
 ['405', '31', '3305'],
 ['731', '59', '7531'],
 ['676', '39', '6028'],
 ['502', '05', '1910'],
 ['485', '30', '8700'],
 ['598', '47', '9715'],
 ['701', '69', '8742'],
 ['575', '67', '1508'],
 ['541', '08', '3113'],
 ['246', '11', '3901'],
 ['674', '15', '9296'],
 ['305', '18', '3552'],
 ['493', '65', '6248'],
 ['438', '01', '4015'],
 ['709', '58', '4068'],
 ['795', '49', '7276'],
 ['556', '72', '8512'],
 ['627', '95', '3243'],
 ['686', '41', '0932'],
 ['510', '09', '5628'],
 ['608', '04', '3797'],
 ['148', '82', '2527'],
 ['437', '53', '3084'],
 ['632', '32', '4574'],
 ['556', '97', '7101'],
 ['862', '59', '8517'],
 ['401', '18', '8016'],
 ['420', '18', '8989'],
 ['277', '63', '2961'],
 ['573', '98', '8548'],
 ['620', '02', '2046'],
 ['282', '35', '2475'],
 ['511', '54', '3087'],
 ['726', '29', '6793'],
 ['387', '49', '4215'],
 ['862', '17', '9201'],
 ['291', '21', '5991'],
 ['602', '80', '9671'],
 ['347', '72', '6115'],
 ['209', '61', '0206'],
 ['595', '27', '4851'],
 ['189', '52', '0236'],
 ['503', '07', '0930'],
 ['413', '20', '6708'],
 ['425', '85', '2085'],
 ['521', '18', '7827'],
 ['220', '28', '1851'],
 ['600', '38', '9738'],
 ['734', '91', '1155'],
 ['451', '28', '5717'],
 ['609', '81', '8548'],
 ['133', '14', '7229'],
 ['534', '01', '4457'],
 ['719', '89', '8991'],
 ['286', '62', '6248'],
 ['339', '38', '9982'],
 ['827', '44', '5872'],
 ['827', '77', '7633'],
 ['287', '83', '1405'],
 ['435', '13', '4908'],
 ['857', '67', '9057'],
 ['236', '27', '1144'],
 ['892', '05', '6689'],
 ['583', '41', '4548'],
 ['339', '12', '4827'],
 ['643', '38', '7867'],
 ['308', '81', '0538'],
 ['358', '88', '9262'],
 ['460', '35', '4390'],
 ['343', '87', '0864'],
 ['173', '50', '1108'],
 ['243', '47', '2663'],
 ['841', '18', '8232'],
 ['701', '23', '5550'],
 ['647', '50', '1224'],
 ['541', '48', '8554'],
 ['539', '21', '7227'],
 ['213', '32', '1216'],
 ['747', '58', '7183'],
 ['582', '52', '8065'],
 ['210', '57', '1719'],
 ['399', '69', '4630'],
 ['134', '75', '2619'],
 ['356', '44', '8813'],
 ['198', '66', '9832'],
 ['283', '26', '5248'],
 ['712', '39', '0363'],
 ['218', '59', '9410'],
 ['174', '75', '0888'],
 ['866', '99', '7614'],
 ['134', '54', '4720'],
 ['760', '90', '2357'],
 ['514', '37', '2845'],
 ['698', '98', '5964'],
 ['718', '57', '9773'],
 ['651', '88', '7328'],
 ['241', '11', '2261'],
 ['408', '26', '9866'],
 ['834', '83', '1826'],
 ['343', '61', '3544'],
 ['239', '48', '4278'],
 ['355', '34', '6244'],
 ['550', '84', '8664'],
 ['339', '96', '8318'],
 ['458', '61', '0011'],
 ['592', '34', '6155'],
 ['797', '88', '0493'],
 ['207', '73', '1363'],
 ['390', '31', '6381'],
 ['443', '82', '0585'],
 ['339', '18', '7061'],
 ['359', '90', '3665'],
 ['375', '72', '3056'],
 ['127', '47', '6963'],
 ['278', '86', '2735'],
 ['695', '28', '6250'],
 ['379', '17', '6588'],
 ['227', '50', '3718'],
 ['302', '15', '2162'],
 ['788', '07', '8452'],
 ['560', '49', '6611'],
 ['880', '35', '0356'],
 ['585', '11', '6748'],
 ['470', '31', '3286'],
 ['152', '68', '2907'],
 ['123', '35', '4896'],
 ['258', '69', '7810'],
 ['334', '64', '2006'],
 ['219', '61', '4139'],
 ['881', '41', '7302'],
 ['373', '09', '4567'],
 ['642', '30', '6693'],
 ['484', '22', '8230'],
 ['830', '58', '2383'],
 ['559', '98', '9873'],
 ['544', '32', '5024'],
 ['318', '12', '0304'],
 ['349', '97', '8902'],
 ['421', '95', '9805'],
 ['277', '35', '5865'],
 ['789', '23', '8625'],
 ['284', '54', '4231'],
 ['443', '59', '0061'],
 ['509', '29', '3912'],
 ['327', '40', '9673'],
 ['840', '19', '2096'],
 ['828', '46', '6863'],
 ['641', '96', '3695'],
 ['420', '97', '3340'],
 ['436', '54', '4512'],
 ['670', '79', '6321'],
 ['852', '62', '7105'],
 ['598', '06', '7312'],
 ['135', '13', '8269'],
 ['816', '57', '2053'],
 ['628', '90', '8624'],
 ['856', '66', '2701'],
 ['308', '39', '1707'],
 ['149', '61', '1929'],
 ['655', '07', '2265'],
 ['589', '02', '8023'],
 ['420', '04', '7590'],
 ['182', '88', '2763'],
 ['188', '55', '0967'],
 ['610', '46', '4100'],
 ['318', '81', '2368'],
 ['364', '33', '8584'],
 ['665', '63', '9737'],
 ['695', '09', '5146'],
 ['155', '45', '3814'],
 ['794', '32', '2436'],
 ['131', '15', '8856'],
 ['273', '84', '2164'],
 ['706', '36', '6154'],
 ['778', '89', '7974'],
 ['574', '31', '8277'],
 ['859', '71', '0933'],
 ['740', '11', '5257'],
 ['369', '82', '2676'],
 ['563', '47', '4072'],
 ['742', '04', '5161'],
 ['149', '15', '7606'],
 ['133', '77', '3154'],
 ['169', '52', '4504'],
 ['250', '81', '7186'],
 ['562', '12', '5430'],
 ['816', '72', '8853'],
 ['491', '38', '3499'],
 ['322', '02', '2271'],
 ['842', '29', '4695'],
 ['725', '67', '2480'],
 ['641', '51', '2661'],
 ['714', '02', '3114'],
 ['518', '17', '2983'],
 ['779', '42', '2410'],
 ['190', '14', '3147'],
 ['408', '66', '6712'],
 ['679', '22', '6530'],
 ['588', '47', '8641'],
 ['642', '61', '4706'],
 ['576', '31', '4774'],
 ['556', '41', '6224'],
 ['811', '03', '8790'],
 ['242', '11', '3142'],
 ['752', '23', '3760'],
 ['274', '05', '5470'],
 ['648', '94', '3045'],
 ['130', '67', '4723'],
 ['528', '87', '5606'],
 ['320', '85', '2052'],
 ['370', '96', '0655'],
 ['105', '10', '6182'],
 ['510', '79', '0415'],
 ['241', '96', '5076'],
 ['767', '97', '4650'],
 ['648', '83', '1321'],
 ['173', '57', '2300'],
 ['305', '03', '2383'],
 ['394', '55', '6384'],
 ['266', '20', '6657'],
 ['689', '05', '1884'],
 ['196', '01', '2849'],
 ['372', '62', '5264'],
 ['800', '09', '8606'],
 ['182', '52', '7000'],
 ['826', '58', '8051'],
 ['868', '06', '0466'],
 ['751', '41', '9720'],
 ['626', '43', '7888'],
 ['176', '64', '7711'],
 ['191', '29', '0321'],
 ['729', '06', '2010'],
 ['640', '48', '5028'],
 ['186', '79', '9562'],
 ['834', '45', '5519'],
 ['162', '65', '8559'],
 ['760', '27', '5490'],
 ['445', '30', '9252'],
 ['786', '94', '2700'],
 ['728', '88', '7867'],
 ['183', '21', '3799'],
 ['268', '20', '3585'],
 ['735', '32', '9839'],
 ['258', '92', '7466'],
 ['857', '16', '3520'],
 ['482', '17', '1179'],
 ['788', '21', '5741'],
 ['821', '14', '9046'],
 ['418', '05', '0656'],
 ['678', '79', '0726'],
 ['776', '68', '1096'],
 ['592', '46', '1692'],
 ['434', '35', '9162'],
 ['149', '14', '0304'],
 ['442', '44', '6497'],
 ['174', '64', '0215'],
 ['210', '74', '9613'],
 ['299', '29', '0180'],
 ['247', '11', '2470'],
 ['635', '28', '5728'],
 ['756', '49', '0168'],
 ['438', '23', '1242'],
 ['238', '45', '6950'],
 ['607', '65', '2441'],
 ['386', '27', '7606'],
 ['137', '63', '5492'],
 ['197', '77', '7132'],
 ['805', '86', '0265'],
 ['733', '29', '1227'],
 ['451', '73', '2711'],
 ['373', '14', '0504'],
 ['546', '80', '2899'],
 ['345', '68', '9016'],
 ['390', '17', '5806'],
 ['457', '13', '1708'],
 ['664', '14', '2882'],
 ['487', '79', '6868'],
 ['314', '23', '4520'],
 ['210', '30', '7976'],
 ['585', '86', '8361'],
 ['807', '14', '7833'],
 ['775', '72', '1988'],
 ['288', '38', '3758'],
 ['652', '43', '6591'],
 ['785', '96', '0615'],
 ['406', '46', '7107'],
 ['250', '17', '5703'],
 ['156', '95', '3964'],
 ['842', '40', '8179'],
 ['525', '09', '8450'],
 ['410', '67', '1709'],
 ['587', '73', '4862'],
 ['787', '87', '2010'],
 ['593', '14', '4239'],
 ['801', '88', '0346'],
 ['388', '76', '2555'],
 ['711', '31', '1234'],
 ['886', '54', '6089'],
 ['707', '32', '7409'],
 ['759', '98', '4285'],
 ['201', '63', '8275'],
 ['471', '06', '8611'],
 ['200', '16', '5952'],
 ['120', '54', '2248'],
 ['102', '77', '2261'],
 ['875', '31', '8302'],
 ['102', '06', '2002'],
 ['457', '94', '0464'],
 ['629', '42', '4133'],
 ['534', '53', '3526'],
 ['307', '04', '2070'],
 ['468', '99', '7231'],
 ['516', '77', '6464'],
 ['404', '91', '5964'],
 ['886', '77', '9084'],
 ['790', '38', '4466'],
 ['704', '10', '4056'],
 ['497', '37', '6538'],
 ['651', '96', '5970'],
 ['400', '80', '4065'],
 ['744', '16', '7898'],
 ['263', '12', '5321'],
 ['702', '72', '0487'],
 ['605', '83', '1050'],
 ['443', '60', '9639'],
 ['864', '24', '7918'],
 ['359', '94', '5395'],
 ['401', '09', '4232'],
 ['751', '15', '6198'],
 ['324', '41', '6833'],
 ['474', '33', '8305'],
 ['759', '29', '9521'],
 ['831', '81', '6575'],
 ['220', '68', '6701'],
 ['618', '34', '8551'],
 ['257', '60', '7754'],
 ['559', '61', '5987'],
 ['189', '55', '2313'],
 ['565', '91', '4567'],
 ['380', '60', '5336'],
 ['815', '04', '6282'],
 ['674', '56', '6360'],
 ['778', '34', '2523'],
 ['499', '27', '7781'],
 ['477', '59', '2456'],
 ['832', '51', '6761'],
 ['869', '11', '3082'],
 ['190', '59', '3964'],
 ['366', '43', '6862'],
 ['186', '43', '8965'],
 ['784', '21', '9238'],
 ['276', '75', '6884'],
 ['109', '86', '4363'],
 ['569', '76', '2760'],
 ['222', '42', '0244'],
 ['760', '53', '9233'],
 ['538', '22', '0304'],
 ['416', '17', '9926'],
 ['237', '44', '6163'],
 ['636', '17', '0325'],
 ['343', '75', '9322'],

In [ ]:
#splitting using a regular expression
[re.split('\s+',x) for x in df['Product line']]

[['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],

In [ ]:
#how is this different?
[re.split(' ',x) for x in df['Product line']]

[['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],

In [ ]:
#An alternate way of doing the above
regex_exp = re.compile('\s+')
[regex_exp.split(x) for x in df['Product line']]

[['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Electronic', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Sports', 'and', 'travel'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Home', 'and', 'lifestyle'],
 ['Food', 'and', 'beverages'],
 ['Health', 'and', 'beauty'],
 ['Health', 'and', 'beauty'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Fashion', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Food', 'and', 'beverages'],
 ['Electronic', 'accessories'],
 ['Home', 'and', 'lifestyle'],
 ['Health', 'and', 'beauty'],
 ['Fashion', 'accessories'],
 ['Sports', 'and', 'travel'],
 ['Electronic', 'accessories'],
 ['Electronic', 'accessories'],
 ['Health', 'and', 'beauty'],
 ['Home', 'and', 'lifestyle'],
 ['Sports', 'and', 'travel'],
 ['Fashion', 'accessories'],
 ['Electronic', 'accessories'],

In [ ]:
type(regex_exp)

re.Pattern

In [ ]:
l2

[['750', '67', '8428'],
 ['226', '31', '3081'],
 ['631', '41', '3108'],
 ['123', '19', '1176'],
 ['373', '73', '7910'],
 ['699', '14', '3026'],
 ['355', '53', '5943'],
 ['315', '22', '5665'],
 ['665', '32', '9167'],
 ['692', '92', '5582'],
 ['351', '62', '0822'],
 ['529', '56', '3974'],
 ['365', '64', '0515'],
 ['252', '56', '2699'],
 ['829', '34', '3910'],
 ['299', '46', '1805'],
 ['656', '95', '9349'],
 ['765', '26', '6951'],
 ['329', '62', '1586'],
 ['319', '50', '3348'],
 ['300', '71', '4605'],
 ['371', '85', '5789'],
 ['273', '16', '6619'],
 ['636', '48', '8204'],
 ['549', '59', '1358'],
 ['227', '03', '5010'],
 ['649', '29', '6775'],
 ['189', '17', '4241'],
 ['145', '94', '9061'],
 ['848', '62', '7243'],
 ['871', '79', '8483'],
 ['149', '71', '6266'],
 ['640', '49', '2076'],
 ['595', '11', '5460'],
 ['183', '56', '6882'],
 ['232', '16', '2483'],
 ['129', '29', '8530'],
 ['272', '65', '1806'],
 ['333', '73', '7901'],
 ['777', '82', '7220'],
 ['280', '35', '5823'],
 ['554', '53', '8700'],
 ['354', '25', '5821'],
 ['228', '96', '1411'],
 ['617', '15', '4209'],
 ['132', '32', '9879'],
 ['370', '41', '7321'],
 ['727', '46', '3608'],
 ['669', '54', '1719'],
 ['574', '22', '5561'],
 ['326', '78', '5178'],
 ['162', '48', '8011'],
 ['616', '24', '2851'],
 ['778', '71', '5554'],
 ['242', '55', '6721'],
 ['399', '46', '5918'],
 ['106', '35', '6779'],
 ['635', '40', '6220'],
 ['817', '48', '8732'],
 ['120', '06', '4233'],
 ['285', '68', '5083'],
 ['803', '83', '5989'],
 ['347', '34', '2234'],
 ['199', '75', '8169'],
 ['853', '23', '2453'],
 ['877', '22', '3308'],
 ['838', '78', '4295'],
 ['109', '28', '2512'],
 ['232', '11', '3025'],
 ['382', '03', '4532'],
 ['393', '65', '2792'],
 ['796', '12', '2025'],
 ['510', '95', '6347'],
 ['841', '35', '6630'],
 ['287', '21', '9091'],
 ['732', '94', '0499'],
 ['263', '10', '3913'],
 ['381', '20', '0914'],
 ['829', '49', '1914'],
 ['756', '01', '7507'],
 ['870', '72', '4431'],
 ['847', '38', '7188'],
 ['480', '63', '2856'],
 ['787', '56', '0757'],
 ['360', '39', '5055'],
 ['730', '50', '9884'],
 ['362', '58', '8315'],
 ['633', '44', '8566'],
 ['504', '35', '8843'],
 ['318', '68', '5053'],
 ['565', '80', '5980'],
 ['225', '32', '0908'],
 ['873', '51', '0671'],
 ['152', '08', '9985'],
 ['512', '91', '0811'],
 ['594', '34', '4444'],
 ['766', '85', '7061'],
 ['871', '39', '9221'],
 ['865', '92', '6136'],
 ['733', '01', '9107'],
 ['163', '56', '7055'],
 ['189', '98', '2939'],
 ['551', '21', '3069'],
 ['212', '62', '1842'],
 ['716', '39', '1409'],
 ['704', '48', '3927'],
 ['628', '34', '3388'],
 ['630', '74', '5166'],
 ['588', '01', '7461'],
 ['861', '77', '0145'],
 ['479', '26', '8945'],
 ['210', '67', '5886'],
 ['227', '78', '1148'],
 ['645', '44', '1170'],
 ['237', '01', '6122'],
 ['225', '98', '1496'],
 ['291', '32', '1427'],
 ['659', '65', '8956'],
 ['642', '32', '2990'],
 ['378', '24', '2715'],
 ['638', '60', '7125'],
 ['659', '36', '1684'],
 ['219', '22', '9386'],
 ['336', '78', '2147'],
 ['268', '27', '6179'],
 ['668', '90', '8900'],
 ['870', '54', '3162'],
 ['189', '08', '9157'],
 ['663', '86', '9076'],
 ['549', '84', '7482'],
 ['191', '10', '6171'],
 ['802', '70', '5316'],
 ['695', '51', '0018'],
 ['590', '83', '4591'],
 ['483', '71', '1164'],
 ['597', '78', '7908'],
 ['700', '81', '1757'],
 ['354', '39', '5160'],
 ['241', '72', '9525'],
 ['575', '30', '8091'],
 ['731', '81', '9469'],
 ['280', '17', '4359'],
 ['338', '65', '2210'],
 ['488', '25', '4221'],
 ['239', '10', '7476'],
 ['458', '41', '1477'],
 ['685', '64', '1609'],
 ['568', '90', '5112'],
 ['262', '47', '2794'],
 ['238', '49', '0436'],
 ['608', '96', '3517'],
 ['584', '86', '7256'],
 ['746', '94', '0204'],
 ['214', '17', '6927'],
 ['400', '89', '4171'],
 ['782', '95', '9291'],
 ['279', '74', '2924'],
 ['307', '85', '2293'],
 ['743', '04', '1105'],
 ['423', '57', '2993'],
 ['894', '41', '5205'],
 ['275', '28', '0149'],
 ['101', '17', '6199'],
 ['423', '80', '0988'],
 ['548', '46', '9322'],
 ['505', '02', '0892'],
 ['234', '65', '2137'],
 ['687', '47', '8271'],
 ['796', '32', '9050'],
 ['105', '31', '1824'],
 ['249', '42', '3782'],
 ['316', '55', '4634'],
 ['733', '33', '4967'],
 ['608', '27', '6295'],
 ['414', '12', '7047'],
 ['827', '26', '2100'],
 ['175', '54', '2529'],
 ['139', '52', '2867'],
 ['407', '63', '8975'],
 ['342', '65', '4817'],
 ['130', '98', '8941'],
 ['434', '83', '9547'],
 ['851', '28', '6367'],
 ['824', '88', '3614'],
 ['586', '25', '0848'],
 ['895', '66', '0685'],
 ['305', '14', '0245'],
 ['732', '04', '5373'],
 ['400', '60', '7251'],
 ['593', '65', '1552'],
 ['284', '34', '9626'],
 ['437', '58', '8131'],
 ['286', '43', '6208'],
 ['641', '43', '2399'],
 ['831', '07', '6050'],
 ['556', '86', '3144'],
 ['848', '24', '9445'],
 ['856', '22', '8149'],
 ['699', '01', '4164'],
 ['420', '11', '4919'],
 ['606', '80', '4905'],
 ['542', '41', '0513'],
 ['426', '39', '2418'],
 ['875', '46', '5808'],
 ['394', '43', '4238'],
 ['749', '24', '1565'],
 ['672', '51', '8681'],
 ['263', '87', '5680'],
 ['573', '58', '9734'],
 ['817', '69', '8206'],
 ['888', '02', '0338'],
 ['677', '11', '0152'],
 ['142', '63', '6033'],
 ['656', '16', '1063'],
 ['891', '58', '8335'],
 ['802', '43', '8934'],
 ['560', '30', '5617'],
 ['319', '74', '2561'],
 ['549', '03', '9315'],
 ['790', '29', '1172'],
 ['239', '36', '3640'],
 ['468', '01', '2051'],
 ['389', '25', '3394'],
 ['279', '62', '1445'],
 ['213', '72', '6612'],
 ['746', '68', '6593'],
 ['836', '82', '5858'],
 ['583', '72', '1480'],
 ['466', '61', '5506'],
 ['721', '86', '6247'],
 ['289', '65', '5721'],
 ['545', '46', '3100'],
 ['418', '02', '5978'],
 ['269', '04', '5750'],
 ['157', '13', '5295'],
 ['645', '78', '8093'],
 ['211', '30', '9270'],
 ['755', '12', '3214'],
 ['346', '84', '3103'],
 ['478', '06', '7835'],
 ['540', '11', '4336'],
 ['448', '81', '5016'],
 ['142', '72', '4741'],
 ['217', '58', '1179'],
 ['376', '02', '8238'],
 ['530', '90', '9855'],
 ['866', '05', '7563'],
 ['604', '70', '6476'],
 ['799', '71', '1548'],
 ['785', '13', '7708'],
 ['845', '51', '0542'],
 ['662', '47', '5456'],
 ['883', '17', '4236'],
 ['290', '68', '2984'],
 ['704', '11', '6354'],
 ['110', '48', '7033'],
 ['366', '93', '0948'],
 ['729', '09', '9681'],
 ['151', '16', '1484'],
 ['380', '94', '4661'],
 ['850', '41', '9669'],
 ['821', '07', '3596'],
 ['655', '85', '5130'],
 ['447', '15', '7839'],
 ['154', '74', '7179'],
 ['253', '12', '6086'],
 ['808', '65', '0703'],
 ['571', '94', '0759'],
 ['144', '51', '6085'],
 ['731', '14', '2199'],
 ['783', '09', '1637'],
 ['687', '15', '1097'],
 ['126', '54', '1082'],
 ['633', '91', '1052'],
 ['477', '24', '6490'],
 ['566', '19', '5475'],
 ['526', '86', '8552'],
 ['376', '56', '3573'],
 ['537', '72', '0426'],
 ['828', '61', '5674'],
 ['136', '08', '6195'],
 ['523', '38', '0215'],
 ['490', '29', '1201'],
 ['667', '92', '0055'],
 ['565', '17', '3836'],
 ['498', '41', '1961'],
 ['593', '95', '4461'],
 ['226', '71', '3580'],
 ['283', '79', '9594'],
 ['430', '60', '3493'],
 ['139', '20', '0155'],
 ['558', '80', '4082'],
 ['278', '97', '7759'],
 ['316', '68', '6352'],
 ['585', '03', '5943'],
 ['211', '05', '0490'],
 ['727', '75', '6477'],
 ['744', '02', '5987'],
 ['307', '83', '9164'],
 ['779', '06', '0012'],
 ['446', '47', '6729'],
 ['573', '10', '3877'],
 ['735', '06', '4124'],
 ['439', '54', '7422'],
 ['396', '90', '2219'],
 ['411', '77', '0180'],
 ['286', '01', '5402'],
 ['803', '17', '8013'],
 ['512', '98', '1403'],
 ['848', '42', '2560'],
 ['532', '59', '7201'],
 ['181', '94', '6432'],
 ['870', '76', '1733'],
 ['423', '64', '4619'],
 ['227', '07', '4446'],
 ['174', '36', '3675'],
 ['428', '83', '5800'],
 ['603', '07', '0961'],
 ['704', '20', '4138'],
 ['787', '15', '1757'],
 ['649', '11', '3678'],
 ['622', '20', '1945'],
 ['372', '94', '8041'],
 ['563', '91', '7120'],
 ['746', '54', '5508'],
 ['276', '54', '0879'],
 ['815', '11', '1168'],
 ['719', '76', '3868'],
 ['730', '61', '8757'],
 ['340', '66', '0321'],
 ['868', '81', '1752'],
 ['634', '97', '8956'],
 ['566', '71', '1091'],
 ['442', '48', '3607'],
 ['835', '16', '0096'],
 ['527', '09', '6272'],
 ['898', '04', '2717'],
 ['692', '27', '8933'],
 ['633', '09', '3463'],
 ['374', '17', '3652'],
 ['378', '07', '7001'],
 ['433', '75', '6987'],
 ['873', '95', '4984'],
 ['416', '13', '5917'],
 ['150', '89', '8043'],
 ['135', '84', '8019'],
 ['441', '94', '7118'],
 ['725', '96', '3778'],
 ['531', '80', '1784'],
 ['400', '45', '1220'],
 ['860', '79', '0874'],
 ['834', '61', '8124'],
 ['115', '99', '4379'],
 ['565', '67', '6697'],
 ['320', '49', '6392'],
 ['889', '04', '9723'],
 ['632', '90', '0281'],
 ['554', '42', '2417'],
 ['453', '63', '6187'],
 ['578', '80', '7669'],
 ['612', '36', '5536'],
 ['605', '72', '4132'],
 ['471', '41', '2823'],
 ['462', '67', '9126'],
 ['272', '27', '9238'],
 ['834', '25', '9262'],
 ['122', '61', '9553'],
 ['468', '88', '0009'],
 ['613', '59', '9758'],
 ['254', '31', '0042'],
 ['201', '86', '2184'],
 ['261', '12', '8671'],
 ['730', '70', '9830'],
 ['382', '25', '8917'],
 ['422', '29', '8786'],
 ['667', '23', '5919'],
 ['843', '01', '4703'],
 ['743', '88', '1662'],
 ['595', '86', '2894'],
 ['182', '69', '8360'],
 ['289', '15', '7034'],
 ['462', '78', '5240'],
 ['868', '52', '7573'],
 ['153', '58', '4872'],
 ['662', '72', '2873'],
 ['525', '88', '7307'],
 ['689', '16', '9784'],
 ['725', '56', '0833'],
 ['394', '41', '0748'],
 ['596', '42', '3999'],
 ['541', '89', '9860'],
 ['173', '82', '9529'],
 ['563', '36', '9814'],
 ['308', '47', '4913'],
 ['885', '17', '6250'],
 ['726', '27', '2396'],
 ['316', '01', '3952'],
 ['760', '54', '1821'],
 ['793', '10', '3222'],
 ['346', '12', '3257'],
 ['110', '05', '6330'],
 ['651', '61', '0874'],
 ['236', '86', '3015'],
 ['831', '64', '0259'],
 ['587', '03', '7455'],
 ['882', '40', '4577'],
 ['732', '67', '5346'],
 ['725', '32', '9708'],
 ['256', '08', '8343'],
 ['372', '26', '1506'],
 ['244', '08', '0162'],
 ['569', '71', '4390'],
 ['132', '23', '6451'],
 ['696', '90', '2548'],
 ['472', '15', '9636'],
 ['268', '03', '6164'],
 ['750', '57', '9686'],
 ['186', '09', '3669'],
 ['848', '07', '1692'],
 ['745', '71', '3520'],
 ['266', '76', '6436'],
 ['740', '22', '2500'],
 ['271', '88', '8734'],
 ['301', '81', '8610'],
 ['489', '64', '4354'],
 ['198', '84', '7132'],
 ['269', '10', '8440'],
 ['650', '98', '6268'],
 ['741', '73', '3559'],
 ['325', '77', '6186'],
 ['286', '75', '7818'],
 ['574', '57', '9721'],
 ['459', '50', '7686'],
 ['616', '87', '0016'],
 ['837', '55', '7229'],
 ['751', '69', '0068'],
 ['257', '73', '1380'],
 ['345', '08', '4992'],
 ['549', '96', '4200'],
 ['810', '60', '6344'],
 ['450', '28', '2866'],
 ['394', '30', '3170'],
 ['138', '17', '5109'],
 ['192', '98', '7397'],
 ['301', '11', '9629'],
 ['390', '80', '5128'],
 ['235', '46', '8343'],
 ['453', '12', '7053'],
 ['296', '11', '7041'],
 ['449', '27', '2918'],
 ['891', '01', '7034'],
 ['744', '09', '5786'],
 ['727', '17', '0390'],
 ['568', '88', '3448'],
 ['187', '83', '5490'],
 ['767', '54', '1907'],
 ['710', '46', '4433'],
 ['533', '33', '5337'],
 ['325', '90', '8763'],
 ['729', '46', '7422'],
 ['639', '76', '1242'],
 ['234', '03', '4040'],
 ['326', '71', '2155'],
 ['320', '32', '8842'],
 ['470', '32', '9057'],
 ['878', '30', '2331'],
 ['440', '59', '5691'],
 ['554', '53', '3790'],
 ['746', '19', '0921'],
 ['233', '34', '0817'],
 ['767', '05', '1286'],
 ['340', '21', '9136'],
 ['405', '31', '3305'],
 ['731', '59', '7531'],
 ['676', '39', '6028'],
 ['502', '05', '1910'],
 ['485', '30', '8700'],
 ['598', '47', '9715'],
 ['701', '69', '8742'],
 ['575', '67', '1508'],
 ['541', '08', '3113'],
 ['246', '11', '3901'],
 ['674', '15', '9296'],
 ['305', '18', '3552'],
 ['493', '65', '6248'],
 ['438', '01', '4015'],
 ['709', '58', '4068'],
 ['795', '49', '7276'],
 ['556', '72', '8512'],
 ['627', '95', '3243'],
 ['686', '41', '0932'],
 ['510', '09', '5628'],
 ['608', '04', '3797'],
 ['148', '82', '2527'],
 ['437', '53', '3084'],
 ['632', '32', '4574'],
 ['556', '97', '7101'],
 ['862', '59', '8517'],
 ['401', '18', '8016'],
 ['420', '18', '8989'],
 ['277', '63', '2961'],
 ['573', '98', '8548'],
 ['620', '02', '2046'],
 ['282', '35', '2475'],
 ['511', '54', '3087'],
 ['726', '29', '6793'],
 ['387', '49', '4215'],
 ['862', '17', '9201'],
 ['291', '21', '5991'],
 ['602', '80', '9671'],
 ['347', '72', '6115'],
 ['209', '61', '0206'],
 ['595', '27', '4851'],
 ['189', '52', '0236'],
 ['503', '07', '0930'],
 ['413', '20', '6708'],
 ['425', '85', '2085'],
 ['521', '18', '7827'],
 ['220', '28', '1851'],
 ['600', '38', '9738'],
 ['734', '91', '1155'],
 ['451', '28', '5717'],
 ['609', '81', '8548'],
 ['133', '14', '7229'],
 ['534', '01', '4457'],
 ['719', '89', '8991'],
 ['286', '62', '6248'],
 ['339', '38', '9982'],
 ['827', '44', '5872'],
 ['827', '77', '7633'],
 ['287', '83', '1405'],
 ['435', '13', '4908'],
 ['857', '67', '9057'],
 ['236', '27', '1144'],
 ['892', '05', '6689'],
 ['583', '41', '4548'],
 ['339', '12', '4827'],
 ['643', '38', '7867'],
 ['308', '81', '0538'],
 ['358', '88', '9262'],
 ['460', '35', '4390'],
 ['343', '87', '0864'],
 ['173', '50', '1108'],
 ['243', '47', '2663'],
 ['841', '18', '8232'],
 ['701', '23', '5550'],
 ['647', '50', '1224'],
 ['541', '48', '8554'],
 ['539', '21', '7227'],
 ['213', '32', '1216'],
 ['747', '58', '7183'],
 ['582', '52', '8065'],
 ['210', '57', '1719'],
 ['399', '69', '4630'],
 ['134', '75', '2619'],
 ['356', '44', '8813'],
 ['198', '66', '9832'],
 ['283', '26', '5248'],
 ['712', '39', '0363'],
 ['218', '59', '9410'],
 ['174', '75', '0888'],
 ['866', '99', '7614'],
 ['134', '54', '4720'],
 ['760', '90', '2357'],
 ['514', '37', '2845'],
 ['698', '98', '5964'],
 ['718', '57', '9773'],
 ['651', '88', '7328'],
 ['241', '11', '2261'],
 ['408', '26', '9866'],
 ['834', '83', '1826'],
 ['343', '61', '3544'],
 ['239', '48', '4278'],
 ['355', '34', '6244'],
 ['550', '84', '8664'],
 ['339', '96', '8318'],
 ['458', '61', '0011'],
 ['592', '34', '6155'],
 ['797', '88', '0493'],
 ['207', '73', '1363'],
 ['390', '31', '6381'],
 ['443', '82', '0585'],
 ['339', '18', '7061'],
 ['359', '90', '3665'],
 ['375', '72', '3056'],
 ['127', '47', '6963'],
 ['278', '86', '2735'],
 ['695', '28', '6250'],
 ['379', '17', '6588'],
 ['227', '50', '3718'],
 ['302', '15', '2162'],
 ['788', '07', '8452'],
 ['560', '49', '6611'],
 ['880', '35', '0356'],
 ['585', '11', '6748'],
 ['470', '31', '3286'],
 ['152', '68', '2907'],
 ['123', '35', '4896'],
 ['258', '69', '7810'],
 ['334', '64', '2006'],
 ['219', '61', '4139'],
 ['881', '41', '7302'],
 ['373', '09', '4567'],
 ['642', '30', '6693'],
 ['484', '22', '8230'],
 ['830', '58', '2383'],
 ['559', '98', '9873'],
 ['544', '32', '5024'],
 ['318', '12', '0304'],
 ['349', '97', '8902'],
 ['421', '95', '9805'],
 ['277', '35', '5865'],
 ['789', '23', '8625'],
 ['284', '54', '4231'],
 ['443', '59', '0061'],
 ['509', '29', '3912'],
 ['327', '40', '9673'],
 ['840', '19', '2096'],
 ['828', '46', '6863'],
 ['641', '96', '3695'],
 ['420', '97', '3340'],
 ['436', '54', '4512'],
 ['670', '79', '6321'],
 ['852', '62', '7105'],
 ['598', '06', '7312'],
 ['135', '13', '8269'],
 ['816', '57', '2053'],
 ['628', '90', '8624'],
 ['856', '66', '2701'],
 ['308', '39', '1707'],
 ['149', '61', '1929'],
 ['655', '07', '2265'],
 ['589', '02', '8023'],
 ['420', '04', '7590'],
 ['182', '88', '2763'],
 ['188', '55', '0967'],
 ['610', '46', '4100'],
 ['318', '81', '2368'],
 ['364', '33', '8584'],
 ['665', '63', '9737'],
 ['695', '09', '5146'],
 ['155', '45', '3814'],
 ['794', '32', '2436'],
 ['131', '15', '8856'],
 ['273', '84', '2164'],
 ['706', '36', '6154'],
 ['778', '89', '7974'],
 ['574', '31', '8277'],
 ['859', '71', '0933'],
 ['740', '11', '5257'],
 ['369', '82', '2676'],
 ['563', '47', '4072'],
 ['742', '04', '5161'],
 ['149', '15', '7606'],
 ['133', '77', '3154'],
 ['169', '52', '4504'],
 ['250', '81', '7186'],
 ['562', '12', '5430'],
 ['816', '72', '8853'],
 ['491', '38', '3499'],
 ['322', '02', '2271'],
 ['842', '29', '4695'],
 ['725', '67', '2480'],
 ['641', '51', '2661'],
 ['714', '02', '3114'],
 ['518', '17', '2983'],
 ['779', '42', '2410'],
 ['190', '14', '3147'],
 ['408', '66', '6712'],
 ['679', '22', '6530'],
 ['588', '47', '8641'],
 ['642', '61', '4706'],
 ['576', '31', '4774'],
 ['556', '41', '6224'],
 ['811', '03', '8790'],
 ['242', '11', '3142'],
 ['752', '23', '3760'],
 ['274', '05', '5470'],
 ['648', '94', '3045'],
 ['130', '67', '4723'],
 ['528', '87', '5606'],
 ['320', '85', '2052'],
 ['370', '96', '0655'],
 ['105', '10', '6182'],
 ['510', '79', '0415'],
 ['241', '96', '5076'],
 ['767', '97', '4650'],
 ['648', '83', '1321'],
 ['173', '57', '2300'],
 ['305', '03', '2383'],
 ['394', '55', '6384'],
 ['266', '20', '6657'],
 ['689', '05', '1884'],
 ['196', '01', '2849'],
 ['372', '62', '5264'],
 ['800', '09', '8606'],
 ['182', '52', '7000'],
 ['826', '58', '8051'],
 ['868', '06', '0466'],
 ['751', '41', '9720'],
 ['626', '43', '7888'],
 ['176', '64', '7711'],
 ['191', '29', '0321'],
 ['729', '06', '2010'],
 ['640', '48', '5028'],
 ['186', '79', '9562'],
 ['834', '45', '5519'],
 ['162', '65', '8559'],
 ['760', '27', '5490'],
 ['445', '30', '9252'],
 ['786', '94', '2700'],
 ['728', '88', '7867'],
 ['183', '21', '3799'],
 ['268', '20', '3585'],
 ['735', '32', '9839'],
 ['258', '92', '7466'],
 ['857', '16', '3520'],
 ['482', '17', '1179'],
 ['788', '21', '5741'],
 ['821', '14', '9046'],
 ['418', '05', '0656'],
 ['678', '79', '0726'],
 ['776', '68', '1096'],
 ['592', '46', '1692'],
 ['434', '35', '9162'],
 ['149', '14', '0304'],
 ['442', '44', '6497'],
 ['174', '64', '0215'],
 ['210', '74', '9613'],
 ['299', '29', '0180'],
 ['247', '11', '2470'],
 ['635', '28', '5728'],
 ['756', '49', '0168'],
 ['438', '23', '1242'],
 ['238', '45', '6950'],
 ['607', '65', '2441'],
 ['386', '27', '7606'],
 ['137', '63', '5492'],
 ['197', '77', '7132'],
 ['805', '86', '0265'],
 ['733', '29', '1227'],
 ['451', '73', '2711'],
 ['373', '14', '0504'],
 ['546', '80', '2899'],
 ['345', '68', '9016'],
 ['390', '17', '5806'],
 ['457', '13', '1708'],
 ['664', '14', '2882'],
 ['487', '79', '6868'],
 ['314', '23', '4520'],
 ['210', '30', '7976'],
 ['585', '86', '8361'],
 ['807', '14', '7833'],
 ['775', '72', '1988'],
 ['288', '38', '3758'],
 ['652', '43', '6591'],
 ['785', '96', '0615'],
 ['406', '46', '7107'],
 ['250', '17', '5703'],
 ['156', '95', '3964'],
 ['842', '40', '8179'],
 ['525', '09', '8450'],
 ['410', '67', '1709'],
 ['587', '73', '4862'],
 ['787', '87', '2010'],
 ['593', '14', '4239'],
 ['801', '88', '0346'],
 ['388', '76', '2555'],
 ['711', '31', '1234'],
 ['886', '54', '6089'],
 ['707', '32', '7409'],
 ['759', '98', '4285'],
 ['201', '63', '8275'],
 ['471', '06', '8611'],
 ['200', '16', '5952'],
 ['120', '54', '2248'],
 ['102', '77', '2261'],
 ['875', '31', '8302'],
 ['102', '06', '2002'],
 ['457', '94', '0464'],
 ['629', '42', '4133'],
 ['534', '53', '3526'],
 ['307', '04', '2070'],
 ['468', '99', '7231'],
 ['516', '77', '6464'],
 ['404', '91', '5964'],
 ['886', '77', '9084'],
 ['790', '38', '4466'],
 ['704', '10', '4056'],
 ['497', '37', '6538'],
 ['651', '96', '5970'],
 ['400', '80', '4065'],
 ['744', '16', '7898'],
 ['263', '12', '5321'],
 ['702', '72', '0487'],
 ['605', '83', '1050'],
 ['443', '60', '9639'],
 ['864', '24', '7918'],
 ['359', '94', '5395'],
 ['401', '09', '4232'],
 ['751', '15', '6198'],
 ['324', '41', '6833'],
 ['474', '33', '8305'],
 ['759', '29', '9521'],
 ['831', '81', '6575'],
 ['220', '68', '6701'],
 ['618', '34', '8551'],
 ['257', '60', '7754'],
 ['559', '61', '5987'],
 ['189', '55', '2313'],
 ['565', '91', '4567'],
 ['380', '60', '5336'],
 ['815', '04', '6282'],
 ['674', '56', '6360'],
 ['778', '34', '2523'],
 ['499', '27', '7781'],
 ['477', '59', '2456'],
 ['832', '51', '6761'],
 ['869', '11', '3082'],
 ['190', '59', '3964'],
 ['366', '43', '6862'],
 ['186', '43', '8965'],
 ['784', '21', '9238'],
 ['276', '75', '6884'],
 ['109', '86', '4363'],
 ['569', '76', '2760'],
 ['222', '42', '0244'],
 ['760', '53', '9233'],
 ['538', '22', '0304'],
 ['416', '17', '9926'],
 ['237', '44', '6163'],
 ['636', '17', '0325'],
 ['343', '75', '9322'],

In [ ]:
df['id1'] = pd.DataFrame([x[0] for x in l2])
df['id2'] = pd.DataFrame([x[1] for x in l2])
df['id3'] = pd.DataFrame([x[2] for x in l2])

In [ ]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,...,gross margin percentage,gross income,Rating,sal,price_disc,cat_price_disc,Total_q,id1,id2,id3
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,10.00,7,26.1415,548.9715,...,4.761905,26.1415,9.1,30,"(0, 10]",very low,"(471.35, 1042.65]",750,67,8428
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,...,4.761905,3.8200,9.6,50,"(10, 20]",low,"(10.677000000000001, 124.422]",226,31,3081
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,...,4.761905,16.2155,7.4,30,"(40, 50]",very high,"(253.848, 471.35]",631,41,3108
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,10.00,8,23.2880,489.0480,...,4.761905,23.2880,8.4,30,"(0, 10]",very low,"(471.35, 1042.65]",123,19,1176
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,10.00,7,30.2085,634.3785,...,4.761905,30.2085,5.3,30,"(0, 10]",very low,"(471.35, 1042.65]",373,73,7910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,...,4.761905,2.0175,6.2,50,"(40, 50]",very high,"(10.677000000000001, 124.422]",233,67,5758
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,10.00,10,48.6900,1022.4900,...,4.761905,48.6900,4.4,40,"(0, 10]",very low,"(471.35, 1042.65]",303,96,2227
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,...,4.761905,1.5920,7.7,30,"(30, 40]",high,"(10.677000000000001, 124.422]",727,02,1313
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,10.00,1,3.2910,69.1110,...,4.761905,3.2910,4.1,30,"(0, 10]",very low,"(10.677000000000001, 124.422]",347,56,2442
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,10.00,7,30.9190,649.2990,...,4.761905,30.9190,6.6,30,"(0, 10]",very low,"(471.35, 1042.65]",849,09,3807

In [ ]:
#remove a sub string from a string or replace it with another one
[x.replace('and','') for x in df['Product line']]
#[x.strip('Sports') for x in df['Product line']] #removes a string from the beginning or the end of a string

['Health  beauty',
 'Electronic accessories',
 'Home  lifestyle',
 'Health  beauty',
 'Sports  travel',
 'Electronic accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Health  beauty',
 'Food  beverages',
 'Fashion accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Food  beverages',
 'Health  beauty',
 'Sports  travel',
 'Health  beauty',
 'Sports  travel',
 'Food  beverages',
 'Home  lifestyle',
 'Electronic accessories',
 'Health  beauty',
 'Home  lifestyle',
 'Electronic accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Fashion accessories',
 'Fashion accessories',
 'Food  beverages',
 'Health  beauty',
 'Fashion accessories',
 'Sports  travel',
 'Sports  travel',
 'Health  beauty',
 'Food  beverages',
 'Sports  travel',
 'Sports  travel',
 'Electronic accessories',
 'Health  beauty',
 'Home  lifestyle',
 'Home  lifestyle',
 'Home  lifestyle',
 'Sports  travel',
 'Food  beverages',
 'Health  beauty',
 'Electronic accessories',
 'Health  beauty',
 'Food  beverages',
 'Electronic accessories',
 'Fashion accessories',
 'Food  beverages',
 'Food  beverages',
 'Fashion accessories',
 'Fashion accessories',
 'Home  lifestyle',
 'Electronic accessories',
 'Home  lifestyle',
 'Health  beauty',
 'Home  lifestyle',
 'Electronic accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Sports  travel',
 'Sports  travel',
 'Health  beauty',
 'Health  beauty',
 'Health  beauty',
 'Fashion accessories',
 'Sports  travel',
 'Health  beauty',
 'Food  beverages',
 'Fashion accessories',
 'Food  beverages',
 'Electronic accessories',
 'Home  lifestyle',
 'Electronic accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Food  beverages',
 'Health  beauty',
 'Health  beauty',
 'Food  beverages',
 'Food  beverages',
 'Food  beverages',
 'Sports  travel',
 'Sports  travel',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Health  beauty',
 'Home  lifestyle',
 'Sports  travel',
 'Sports  travel',
 'Health  beauty',
 'Health  beauty',
 'Electronic accessories',
 'Health  beauty',
 'Electronic accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Fashion accessories',
 'Fashion accessories',
 'Electronic accessories',
 'Food  beverages',
 'Health  beauty',
 'Electronic accessories',
 'Fashion accessories',
 'Sports  travel',
 'Food  beverages',
 'Electronic accessories',
 'Sports  travel',
 'Health  beauty',
 'Fashion accessories',
 'Home  lifestyle',
 'Home  lifestyle',
 'Fashion accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Electronic accessories',
 'Sports  travel',
 'Sports  travel',
 'Home  lifestyle',
 'Fashion accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Fashion accessories',
 'Sports  travel',
 'Sports  travel',
 'Electronic accessories',
 'Health  beauty',
 'Fashion accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Sports  travel',
 'Sports  travel',
 'Health  beauty',
 'Health  beauty',
 'Food  beverages',
 'Home  lifestyle',
 'Health  beauty',
 'Fashion accessories',
 'Health  beauty',
 'Home  lifestyle',
 'Health  beauty',
 'Fashion accessories',
 'Sports  travel',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Food  beverages',
 'Electronic accessories',
 'Home  lifestyle',
 'Health  beauty',
 'Sports  travel',
 'Food  beverages',
 'Sports  travel',
 'Food  beverages',
 'Sports  travel',
 'Food  beverages',
 'Health  beauty',
 'Home  lifestyle',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Health  beauty',
 'Food  beverages',
 'Electronic accessories',
 'Electronic accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Food  beverages',
 'Fashion accessories',
 'Food  beverages',
 'Health  beauty',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Health  beauty',
 'Sports  travel',
 'Food  beverages',
 'Home  lifestyle',
 'Home  lifestyle',
 'Home  lifestyle',
 'Home  lifestyle',
 'Home  lifestyle',
 'Fashion accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Electronic accessories',
 'Fashion accessories',
 'Health  beauty',
 'Home  lifestyle',
 'Health  beauty',
 'Food  beverages',
 'Sports  travel',
 'Electronic accessories',
 'Electronic accessories',
 'Health  beauty',
 'Home  lifestyle',
 'Health  beauty',
 'Electronic accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Sports  travel',
 'Sports  travel',
 'Home  lifestyle',
 'Sports  travel',
 'Electronic accessories',
 'Fashion accessories',
 'Food  beverages',
 'Electronic accessories',
 'Food  beverages',
 'Electronic accessories',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Health  beauty',
 'Electronic accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Electronic accessories',
 'Health  beauty',
 'Fashion accessories',
 'Health  beauty',
 'Sports  travel',
 'Health  beauty',
 'Fashion accessories',
 'Electronic accessories',
 'Fashion accessories',
 'Food  beverages',
 'Health  beauty',
 'Fashion accessories',
 'Home  lifestyle',
 'Home  lifestyle',
 'Home  lifestyle',
 'Electronic accessories',
 'Fashion accessories',
 'Electronic accessories',
 'Food  beverages',
 'Food  beverages',
 'Fashion accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Home  lifestyle',
 'Fashion accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Electronic accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Sports  travel',
 'Sports  travel',
 'Sports  travel',
 'Home  lifestyle',
 'Food  beverages',
 'Home  lifestyle',
 'Home  lifestyle',
 'Sports  travel',
 'Health  beauty',
 'Home  lifestyle',
 'Home  lifestyle',
 'Health  beauty',
 'Fashion accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Fashion accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Home  lifestyle',
 'Sports  travel',
 'Health  beauty',
 'Health  beauty',
 'Health  beauty',
 'Home  lifestyle',
 'Sports  travel',
 'Food  beverages',
 'Home  lifestyle',
 'Electronic accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Food  beverages',
 'Health  beauty',
 'Electronic accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Home  lifestyle',
 'Home  lifestyle',
 'Fashion accessories',
 'Health  beauty',
 'Food  beverages',
 'Electronic accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Electronic accessories',
 'Fashion accessories',
 'Sports  travel',
 'Fashion accessories',
 'Food  beverages',
 'Health  beauty',
 'Electronic accessories',
 'Food  beverages',
 'Food  beverages',
 'Electronic accessories',
 'Health  beauty',
 'Health  beauty',
 'Food  beverages',
 'Health  beauty',
 'Health  beauty',
 'Fashion accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Food  beverages',
 'Food  beverages',
 'Health  beauty',
 'Electronic accessories',
 'Home  lifestyle',
 'Food  beverages',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Electronic accessories',
 'Fashion accessories',
 'Sports  travel',
 'Electronic accessories',
 'Food  beverages',
 'Electronic accessories',
 'Health  beauty',
 'Health  beauty',
 'Food  beverages',
 'Sports  travel',
 'Fashion accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Electronic accessories',
 'Health  beauty',
 'Fashion accessories',
 'Electronic accessories',
 'Fashion accessories',
 'Home  lifestyle',
 'Electronic accessories',
 'Food  beverages',
 'Fashion accessories',
 'Sports  travel',
 'Electronic accessories',
 'Sports  travel',
 'Food  beverages',
 'Food  beverages',
 'Food  beverages',
 'Home  lifestyle',
 'Food  beverages',
 'Fashion accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Electronic accessories',
 'Electronic accessories',
 'Fashion accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Fashion accessories',
 'Electronic accessories',
 'Sports  travel',
 'Electronic accessories',
 'Food  beverages',
 'Food  beverages',
 'Food  beverages',
 'Sports  travel',
 'Food  beverages',
 'Health  beauty',
 'Fashion accessories',
 'Food  beverages',
 'Fashion accessories',
 'Fashion accessories',
 'Electronic accessories',
 'Sports  travel',
 'Health  beauty',
 'Health  beauty',
 'Food  beverages',
 'Home  lifestyle',
 'Health  beauty',
 'Electronic accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Home  lifestyle',
 'Fashion accessories',
 'Fashion accessories',
 'Sports  travel',
 'Food  beverages',
 'Fashion accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Health  beauty',
 'Sports  travel',
 'Health  beauty',
 'Sports  travel',
 'Home  lifestyle',
 'Health  beauty',
 'Home  lifestyle',
 'Health  beauty',
 'Health  beauty',
 'Electronic accessories',
 'Food  beverages',
 'Electronic accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Health  beauty',
 'Food  beverages',
 'Sports  travel',
 'Home  lifestyle',
 'Fashion accessories',
 'Food  beverages',
 'Electronic accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Sports  travel',
 'Sports  travel',
 'Home  lifestyle',
 'Food  beverages',
 'Electronic accessories',
 'Food  beverages',
 'Sports  travel',
 'Home  lifestyle',
 'Fashion accessories',
 'Sports  travel',
 'Health  beauty',
 'Food  beverages',
 'Fashion accessories',
 'Health  beauty',
 'Sports  travel',
 'Electronic accessories',
 'Electronic accessories',
 'Food  beverages',
 'Health  beauty',
 'Electronic accessories',
 'Fashion accessories',
 'Food  beverages',
 'Electronic accessories',
 'Electronic accessories',
 'Food  beverages',
 'Food  beverages',
 'Food  beverages',
 'Sports  travel',
 'Food  beverages',
 'Food  beverages',
 'Sports  travel',
 'Health  beauty',
 'Sports  travel',
 'Food  beverages',
 'Electronic accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Fashion accessories',
 'Health  beauty',
 'Electronic accessories',
 'Health  beauty',
 'Sports  travel',
 'Electronic accessories',
 'Sports  travel',
 'Electronic accessories',
 'Food  beverages',
 'Electronic accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Sports  travel',
 'Sports  travel',
 'Fashion accessories',
 'Fashion accessories',
 'Home  lifestyle',
 'Home  lifestyle',
 'Fashion accessories',
 'Fashion accessories',
 'Health  beauty',
 'Home  lifestyle',
 'Fashion accessories',
 'Sports  travel',
 'Electronic accessories',
 'Food  beverages',
 'Sports  travel',
 'Sports  travel',
 'Sports  travel',
 'Fashion accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Sports  travel',
 'Electronic accessories',
 'Sports  travel',
 'Food  beverages',
 'Health  beauty',
 'Home  lifestyle',
 'Sports  travel',
 'Home  lifestyle',
 'Fashion accessories',
 'Electronic accessories',
 'Sports  travel',
 'Fashion accessories',
 'Health  beauty',
 'Home  lifestyle',
 'Home  lifestyle',
 'Sports  travel',
 'Electronic accessories',
 'Home  lifestyle',
 'Home  lifestyle',
 'Health  beauty',
 'Food  beverages',
 'Sports  travel',
 'Fashion accessories',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Health  beauty',
 'Fashion accessories',
 'Electronic accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Home  lifestyle',
 'Fashion accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Health  beauty',
 'Sports  travel',
 'Electronic accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Fashion accessories',
 'Sports  travel',
 'Sports  travel',
 'Electronic accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Health  beauty',
 'Electronic accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Food  beverages',
 'Food  beverages',
 'Home  lifestyle',
 'Electronic accessories',
 'Food  beverages',
 'Electronic accessories',
 'Electronic accessories',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Fashion accessories',
 'Fashion accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Sports  travel',
 'Food  beverages',
 'Food  beverages',
 'Sports  travel',
 'Fashion accessories',
 'Food  beverages',
 'Food  beverages',
 'Health  beauty',
 'Health  beauty',
 'Food  beverages',
 'Health  beauty',
 'Fashion accessories',
 'Fashion accessories',
 'Sports  travel',
 'Health  beauty',
 'Food  beverages',
 'Sports  travel',
 'Fashion accessories',
 'Health  beauty',
 'Health  beauty',
 'Home  lifestyle',
 'Sports  travel',
 'Sports  travel',
 'Sports  travel',
 'Health  beauty',
 'Food  beverages',
 'Sports  travel',
 'Fashion accessories',
 'Home  lifestyle',
 'Electronic accessories',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Fashion accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Food  beverages',
 'Fashion accessories',
 'Food  beverages',
 'Electronic accessories',
 'Food  beverages',
 'Fashion accessories',
 'Sports  travel',
 'Food  beverages',
 'Sports  travel',
 'Sports  travel',
 'Electronic accessories',
 'Food  beverages',
 'Fashion accessories',
 'Food  beverages',
 'Food  beverages',
 'Home  lifestyle',
 'Fashion accessories',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Health  beauty',
 'Home  lifestyle',
 'Fashion accessories',
 'Sports  travel',
 'Electronic accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Food  beverages',
 'Health  beauty',
 'Health  beauty',
 'Electronic accessories',
 'Food  beverages',
 'Fashion accessories',
 'Food  beverages',
 'Electronic accessories',
 'Electronic accessories',
 'Food  beverages',
 'Electronic accessories',
 'Home  lifestyle',
 'Health  beauty',
 'Fashion accessories',
 'Sports  travel',
 'Electronic accessories',
 'Electronic accessories',
 'Health  beauty',
 'Home  lifestyle',
 'Sports  travel',
 'Fashion accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Fashion accessories',
 'Sports  travel',
 'Fashion accessories',
 'Sports  travel',
 'Sports  travel',
 'Fashion accessories',
 'Food  beverages',
 'Sports  travel',
 'Fashion accessories',
 'Food  beverages',
 'Health  beauty',
 'Health  beauty',
 'Sports  travel',
 'Fashion accessories',
 'Food  beverages',
 'Health  beauty',
 'Health  beauty',
 'Electronic accessories',
 'Fashion accessories',
 'Sports  travel',
 'Food  beverages',
 'Health  beauty',
 'Food  beverages',
 'Electronic accessories',
 'Sports  travel',
 'Fashion accessories',
 'Fashion accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Sports  travel',
 'Home  lifestyle',
 'Sports  travel',
 'Food  beverages',
 'Sports  travel',
 'Food  beverages',
 'Health  beauty',
 'Fashion accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Sports  travel',
 'Home  lifestyle',
 'Electronic accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Food  beverages',
 'Fashion accessories',
 'Health  beauty',
 'Home  lifestyle',
 'Health  beauty',
 'Electronic accessories',
 'Food  beverages',
 'Fashion accessories',
 'Sports  travel',
 'Food  beverages',
 'Home  lifestyle',
 'Electronic accessories',
 'Health  beauty',
 'Fashion accessories',
 'Health  beauty',
 'Fashion accessories',
 'Electronic accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Food  beverages',
 'Food  beverages',
 'Health  beauty',
 'Home  lifestyle',
 'Sports  travel',
 'Fashion accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Health  beauty',
 'Fashion accessories',
 'Electronic accessories',
 'Food  beverages',
 'Health  beauty',
 'Home  lifestyle',
 'Electronic accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Home  lifestyle',
 'Food  beverages',
 'Sports  travel',
 'Home  lifestyle',
 'Sports  travel',
 'Food  beverages',
 'Fashion accessories',
 'Home  lifestyle',
 'Home  lifestyle',
 'Health  beauty',
 'Fashion accessories',
 'Food  beverages',
 'Electronic accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Fashion accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Food  beverages',
 'Food  beverages',
 'Food  beverages',
 'Electronic accessories',
 'Fashion accessories',
 'Health  beauty',
 'Health  beauty',
 'Home  lifestyle',
 'Fashion accessories',
 'Sports  travel',
 'Electronic accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Health  beauty',
 'Sports  travel',
 'Food  beverages',
 'Food  beverages',
 'Food  beverages',
 'Health  beauty',
 'Sports  travel',
 'Sports  travel',
 'Electronic accessories',
 'Health  beauty',
 'Sports  travel',
 'Fashion accessories',
 'Home  lifestyle',
 'Health  beauty',
 'Electronic accessories',
 'Electronic accessories',
 'Health  beauty',
 'Health  beauty',
 'Sports  travel',
 'Fashion accessories',
 'Health  beauty',
 'Home  lifestyle',
 'Electronic accessories',
 'Electronic accessories',
 'Fashion accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Health  beauty',
 'Home  lifestyle',
 'Sports  travel',
 'Electronic accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Electronic accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Electronic accessories',
 'Health  beauty',
 'Fashion accessories',
 'Health  beauty',
 'Electronic accessories',
 'Sports  travel',
 'Electronic accessories',
 'Electronic accessories',
 'Food  beverages',
 'Fashion accessories',
 'Food  beverages',
 'Health  beauty',
 'Food  beverages',
 'Electronic accessories',
 'Home  lifestyle',
 'Sports  travel',
 'Health  beauty',
 'Sports  travel',
 'Sports  travel',
 'Health  beauty',
 'Fashion accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Health  beauty',
 'Sports  travel',
 'Health  beauty',
 'Home  lifestyle',
 'Fashion accessories',
 'Fashion accessories',
 'Sports  travel',
 'Electronic accessories',
 'Sports  travel',
 'Fashion accessories',
 'Electronic accessories',
 'Sports  travel',
 'Food  beverages',
 'Fashion accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Sports  travel',
 'Food  beverages',
 'Fashion accessories',
 'Fashion accessories',
 'Fashion accessories',
 'Health  beauty',
 'Electronic accessories',
 'Health  beauty',
 'Fashion accessories',
 'Food  beverages',
 'Home  lifestyle',
 'Health  beauty',
 'Food  beverages',
 'Home  lifestyle',
 'Sports  travel',
 'Home  lifestyle',
 'Home  lifestyle',
 'Electronic accessories',
 'Health  beauty',
 'Sports  travel',
 'Health  beauty',
 'Food  beverages',
 'Sports  travel',
 'Food  beverages',
 'Fashion accessories',
 'Electronic accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Home  lifestyle',
 'Fashion accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Food  beverages',
 'Fashion accessories',
 'Sports  travel',
 'Home  lifestyle',
 'Food  beverages',
 'Sports  travel',
 'Food  beverages',
 'Electronic accessories',
 'Fashion accessories',
 'Sports  travel',
 'Health  beauty',
 'Electronic accessories',
 'Fashion accessories',
 'Electronic accessories',
 'Electronic accessories',
 'Health  beauty',
 'Fashion accessories',
 'Food  beverages',
 'Health  beauty',
 'Food  beverages',
 'Electronic accessories',
 'Home  lifestyle',
 'Health  beauty',
 'Food  beverages',
 'Health  beauty',
 'Home  lifestyle',
 'Health  beauty',
 'Health  beauty',
 'Food  beverages',
 'Home  lifestyle',
 'Food  beverages',
 'Electronic accessories',
 'Home  lifestyle',
 'Fashion accessories',
 'Food  beverages',
 'Electronic accessories',
 'Sports  travel',
 'Fashion accessories',
 'Home  lifestyle',
 'Electronic accessories',
 'Home  lifestyle',
 'Home  lifestyle',
 'Home  lifestyle',
 'Sports  travel',
 'Sports  travel',
 'Electronic accessories',
 'Sports  travel',

In [ ]:
#searching
[re.search('Sports',x) for x in df['Product line']]

[None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [ ]:
[re.match('Sports',x) for x in df['Product line']]

[None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 <re.Match object; span=(0, 6), match='Sports'>,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [246]:
l4 = [re.findall('Sports',x) for x in df['Product line']]

In [247]:
l4

[[],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 ['Sports'],
 ['Sports'],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 ['Sports'],
 [],
 ['Sports'],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['Sports'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 []]

In [248]:
# Loop giving all the indices with "Sports" in it.
for i in range(len(l4)):
    if l4[i]:
        print(i)

4
15
17
24
31
32
35
36
42
60
62
63
68
84
85
88
91
92
107
110
121
122
126
129
131
132
138
139
140
151
154
159
161
163
169
182
184
200
213
214
216
225
235
252
263
264
265
270
279
282
287
306
310
325
334
337
344
357
359
368
377
380
385
393
405
411
413
428
435
436
441
444
449
462
465
467
471
476
478
482
484
485
495
498
499
500
503
504
506
510
514
519
525
529
542
547
548
566
569
571
574
584
587
592
593
594
597
603
613
615
616
626
630
648
653
658
660
661
664
669
676
681
684
686
688
690
696
709
721
727
742
744
767
770
772
777
778
781
789
797
800
806
812
822
824
825
832
837
839
842
847
861
866
869
873
882
885
889
916
923
924
926
929
937
982
991

In [249]:
#combine both into a single line
l5 = [i for i,result in enumerate([re.findall('Sports',x) for x in df['Product line']]) if result]
l5

[4,
 15,
 17,
 24,
 31,
 32,
 35,
 36,
 42,
 60,
 62,
 63,
 68,
 84,
 85,
 88,
 91,
 92,
 107,
 110,
 121,
 122,
 126,
 129,
 131,
 132,
 138,
 139,
 140,
 151,
 154,
 159,
 161,
 163,
 169,
 182,
 184,
 200,
 213,
 214,
 216,
 225,
 235,
 252,
 263,
 264,
 265,
 270,
 279,
 282,
 287,
 306,
 310,
 325,
 334,
 337,
 344,
 357,
 359,
 368,
 377,
 380,
 385,
 393,
 405,
 411,
 413,
 428,
 435,
 436,
 441,
 444,
 449,
 462,
 465,
 467,
 471,
 476,
 478,
 482,
 484,
 485,
 495,
 498,
 499,
 500,
 503,
 504,
 506,
 510,
 514,
 519,
 525,
 529,
 542,
 547,
 548,
 566,
 569,
 571,
 574,
 584,
 587,
 592,
 593,
 594,
 597,
 603,
 613,
 615,
 616,
 626,
 630,
 648,
 653,
 658,
 660,
 661,
 664,
 669,
 676,
 681,
 684,
 686,
 688,
 690,
 696,
 709,
 721,
 727,
 742,
 744,
 767,
 770,
 772,
 777,
 778,
 781,
 789,
 797,
 800,
 806,
 812,
 822,
 824,
 825,
 832,
 837,
 839,
 842,
 847,
 861,
 866,
 869,
 873,
 882,
 885,
 889,
 916,
 923,
 924,
 926,
 929,
 937,
 982,
 991]

In [251]:
#how do you extract the rows corresponding to these indices?
df.take(l5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,gross margin percentage,gross income,Rating,sal,price_disc,cat_price_disc
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,10.00,7,30.2085,634.3785,2/8/2019,10:37,4.761905,30.2085,5.3,30,"(0, 10]",very low
15,299-46-1805,B,Mandalay,Member,Female,Sports and travel,10.00,6,28.1160,590.4360,1/15/2019,16:19,4.761905,28.1160,4.5,40,"(0, 10]",very low
17,765-26-6951,A,Yangon,Normal,Male,Sports and travel,10.00,6,21.7830,457.4430,1/1/2019,10:39,4.761905,21.7830,6.9,30,"(0, 10]",very low
24,549-59-1358,A,Yangon,Member,Male,Sports and travel,10.00,3,13.2945,279.1845,3/2/2019,17:36,4.761905,13.2945,6.0,30,"(0, 10]",very low
31,149-71-6266,B,Mandalay,Member,Male,Sports and travel,10.00,9,35.1315,737.7615,1/28/2019,12:43,4.761905,35.1315,4.5,40,"(0, 10]",very low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
926,321-49-7382,B,Mandalay,Member,Male,Sports and travel,10.00,1,4.4155,92.7255,2/15/2019,17:38,4.761905,4.4155,5.2,40,"(0, 10]",very low
929,825-94-5922,B,Mandalay,Normal,Male,Sports and travel,25.31,2,2.5310,53.1510,3/2/2019,19:26,4.761905,2.5310,7.2,40,"(20, 30]",medium
937,361-85-2571,A,Yangon,Normal,Female,Sports and travel,10.00,5,22.3700,469.7700,3/30/2019,10:18,4.761905,22.3700,7.4,30,"(0, 10]",very low
982,139-32-4183,A,Yangon,Member,Female,Sports and travel,10.00,9,43.8660,921.1860,3/14/2019,14:19,4.761905,43.8660,7.4,30,"(0, 10]",very low
991,602-16-6955,B,Mandalay,Normal,Female,Sports and travel,10.00,10,38.3000,804.3000,1/24/2019,18:10,4.761905,38.3000,6.0,40,"(0, 10]",very low

### Data Aggregation
Grouping records based on certain conditions and applying various operations on them.<br/>
SPLIT-APPLY-COMBINE Mechanism

<img src="Screenshot.png" alt="Alternative text"/>

In [252]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,gross margin percentage,gross income,Rating,sal,price_disc,cat_price_disc
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,10.00,7,26.1415,548.9715,1/5/2019,13:08,4.761905,26.1415,9.1,30,"(0, 10]",very low
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,4.761905,3.8200,9.6,50,"(10, 20]",low
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,4.761905,16.2155,7.4,30,"(40, 50]",very high
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,10.00,8,23.2880,489.0480,1/27/2019,20:33,4.761905,23.2880,8.4,30,"(0, 10]",very low
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,10.00,7,30.2085,634.3785,2/8/2019,10:37,4.761905,30.2085,5.3,30,"(0, 10]",very low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,4.761905,2.0175,6.2,50,"(40, 50]",very high
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,10.00,10,48.6900,1022.4900,3/2/2019,17:16,4.761905,48.6900,4.4,40,"(0, 10]",very low
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,4.761905,1.5920,7.7,30,"(30, 40]",high
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,10.00,1,3.2910,69.1110,2/22/2019,15:33,4.761905,3.2910,4.1,30,"(0, 10]",very low
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,10.00,7,30.9190,649.2990,2/18/2019,13:28,4.761905,30.9190,6.6,30,"(0, 10]",very low

In [253]:
df.groupby('Gender')

In [256]:
#Group iteration
for name, group in df.groupby('Gender'):
    print(name)
    print(group)

Female
      Invoice ID Branch       City Customer type  Gender  \
0    750-67-8428      A     Yangon        Member  Female
1    226-31-3081      C  Naypyitaw        Normal  Female
6    355-53-5943      A     Yangon        Member  Female
7    315-22-5665      C  Naypyitaw        Normal  Female
8    665-32-9167      A     Yangon        Member  Female
..           ...    ...        ...           ...     ...
990  886-18-2897      A     Yangon        Normal  Female
991  602-16-6955      B   Mandalay        Normal  Female
994  652-49-6720      C  Naypyitaw        Member  Female
996  303-96-2227      B   Mandalay        Normal  Female
999  849-09-3807      A     Yangon        Member  Female

               Product line  Unit price  Quantity   Tax 5%      Total  \
0         Health and beauty       10.00         7  26.1415   548.9715
1    Electronic accessories       15.28         5   3.8200    80.2200
6    Electronic accessories       10.00         6  20.6520   433.6920
7        Home and lifestyle       10.00        10  36.7800   772.3800
8         Health and beauty       36.26         2   3.6260    76.1460
..                      ...         ...       ...      ...        ...
990      Food and beverages       10.00         5  14.1400   296.9400
991       Sports and travel       10.00        10  38.3000   804.3000
994  Electronic accessories       10.00         1   3.0475    63.9975
996      Home and lifestyle       10.00        10  48.6900  1022.4900
999     Fashion accessories       10.00         7  30.9190   649.2990

          Date   Time  gross margin percentage  gross income  Rating  sal  \
0     1/5/2019  13:08                 4.761905       26.1415     9.1   30
1     3/8/2019  10:29                 4.761905        3.8200     9.6   50
6    2/25/2019  14:36                 4.761905       20.6520     5.8   30
7    2/24/2019  11:38                 4.761905       36.7800     8.0   50
8    1/10/2019  17:15                 4.761905        3.6260     7.2   30
..         ...    ...                      ...           ...     ...  ...
990  3/22/2019  19:06                 4.761905       14.1400     4.5   30
991  1/24/2019  18:10                 4.761905       38.3000     6.0   40
994  2/18/2019  11:40                 4.761905        3.0475     5.9   50
996   3/2/2019  17:16                 4.761905       48.6900     4.4   40
999  2/18/2019  13:28                 4.761905       30.9190     6.6   30

    price_disc cat_price_disc
0      (0, 10]       very low
1     (10, 20]            low
6      (0, 10]       very low
7      (0, 10]       very low
8     (30, 40]           high
..         ...            ...
990    (0, 10]       very low
991    (0, 10]       very low
994    (0, 10]       very low
996    (0, 10]       very low
999    (0, 10]       very low

[501 rows x 18 columns]
Male
      Invoice ID Branch       City Customer type Gender  \
2    631-41-3108      A     Yangon        Normal   Male
3    123-19-1176      A     Yangon        Member   Male
4    373-73-7910      A     Yangon        Normal   Male
5    699-14-3026      C  Naypyitaw        Normal   Male
11   529-56-3974      B   Mandalay        Member   Male
..           ...    ...        ...           ...    ...
992  745-74-0715      A     Yangon        Normal   Male
993  690-01-6631      B   Mandalay        Normal   Male
995  233-67-5758      C  Naypyitaw        Normal   Male
997  727-02-1313      A     Yangon        Member   Male
998  347-56-2442      A     Yangon        Normal   Male

               Product line  Unit price  Quantity   Tax 5%     Total  \
2        Home and lifestyle       46.33         7  16.2155  340.5255
3         Health and beauty       10.00         8  23.2880  489.0480
4         Sports and travel       10.00         7  30.2085  634.3785
5    Electronic accessories       10.00         7  29.8865  627.6165
11   Electronic accessories       25.51         4   5.1020  107.1420
..                      ...         ...       ...      ...       ...
992  Electronic accessories       10.00         2   5.8030  121.8630
993     Fashion accessories       17.49        10   8.7450  183.6450
995       Health and beauty       40.35         1   2.0175   42.3675
997      Food and beverages       31.84         1   1.5920   33.4320
998      Home and lifestyle       10.00         1   3.2910   69.1110

          Date   Time  gross margin percentage  gross income  Rating  sal  \
2     3/3/2019  13:23                 4.761905       16.2155     7.4   30
3    1/27/2019  20:33                 4.761905       23.2880     8.4   30
4     2/8/2019  10:37                 4.761905       30.2085     5.3   30
5    3/25/2019  18:30                 4.761905       29.8865     4.1   50
11    3/9/2019  17:03                 4.761905        5.1020     6.8   40
..         ...    ...                      ...           ...     ...  ...
992  3/10/2019  20:46                 4.761905        5.8030     8.8   30
993  2/22/2019  18:35                 4.761905        8.7450     6.6   40
995  1/29/2019  13:46                 4.761905        2.0175     6.2   50
997   2/9/2019  13:22                 4.761905        1.5920     7.7   30
998  2/22/2019  15:33                 4.761905        3.2910     4.1   30

    price_disc cat_price_disc
2     (40, 50]      very high
3      (0, 10]       very low
4      (0, 10]       very low
5      (0, 10]       very low
11    (20, 30]         medium
..         ...            ...
992    (0, 10]       very low
993   (10, 20]            low
995   (40, 50]      very high
997   (30, 40]           high
998    (0, 10]       very low

[499 rows x 18 columns]

In [257]:
df.groupby('Gender')['gross income']

In [258]:
df.groupby('Gender')['gross income'].mean()

Gender
Female    15.956936
Male      14.799487
Name: gross income, dtype: float64

In [259]:
#Hierarchical Grouping
df.groupby(['Gender','Customer type'])['gross income'].mean()

Gender  Customer type
Female  Member           16.082274
        Normal           15.820631
Male    Member           15.094544
        Normal           14.526075
Name: gross income, dtype: float64

In [260]:
#converting the above result to a DataFrame
df_new1 = df.groupby(['Gender','Customer type'])['gross income'].mean().reset_index()
df_new1.columns = ['Gender','Customer type','mean income']
df_new1

   Gender Customer type  mean income
0  Female        Member    16.082274
1  Female        Normal    15.820631
2    Male        Member    15.094544
3    Male        Normal    14.526075

In [261]:
def func(x):
    return x.max() - x.min()

In [262]:
#you can also use user defined functions
df_new2 = df.groupby(['Gender','Customer type'])['gross income'].agg(func).reset_index()
df_new2.columns = ['Gender','Customer type','income difference']
df_new2

   Gender Customer type  income difference
0  Female        Member            49.0230
1  Female        Normal            48.0855
2    Male        Member            44.7415
3    Male        Normal            48.8510

In [263]:
#merging the dataframes
pd.merge(df_new1,df_new2,on=['Gender','Customer type'])

   Gender Customer type  mean income  income difference
0  Female        Member    16.082274            49.0230
1  Female        Normal    15.820631            48.0855
2    Male        Member    15.094544            44.7415
3    Male        Normal    14.526075            48.8510

In [264]:
#Another way to apply a function. This transforms the entire dataframe column directly
#It broadcasts the result to all the rows
df.groupby(['Gender','Customer type'])['gross income'].transform(np.mean)

/var/folders/5q/njvzx9bs35sg0dmp71490x800000gn/T/ipykernel_48745/322141232.py:3: FutureWarning: The provided callable <function mean at 0x10ff9cae0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby(['Gender','Customer type'])['gross income'].transform(np.mean)

0      16.082274
1      15.820631
2      14.526075
3      15.094544
4      14.526075
         ...
995    14.526075
996    15.820631
997    15.094544
998    14.526075
999    16.082274
Name: gross income, Length: 1000, dtype: float64

In [265]:
df['mean income'] = df.groupby(['Gender','Customer type'])['gross income'].transform(np.mean)
df

/var/folders/5q/njvzx9bs35sg0dmp71490x800000gn/T/ipykernel_48745/3683251553.py:1: FutureWarning: The provided callable <function mean at 0x10ff9cae0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df['mean income'] = df.groupby(['Gender','Customer type'])['gross income'].transform(np.mean)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,gross margin percentage,gross income,Rating,sal,price_disc,cat_price_disc,mean income
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,10.00,7,26.1415,548.9715,1/5/2019,13:08,4.761905,26.1415,9.1,30,"(0, 10]",very low,16.082274
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,4.761905,3.8200,9.6,50,"(10, 20]",low,15.820631
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,4.761905,16.2155,7.4,30,"(40, 50]",very high,14.526075
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,10.00,8,23.2880,489.0480,1/27/2019,20:33,4.761905,23.2880,8.4,30,"(0, 10]",very low,15.094544
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,10.00,7,30.2085,634.3785,2/8/2019,10:37,4.761905,30.2085,5.3,30,"(0, 10]",very low,14.526075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,4.761905,2.0175,6.2,50,"(40, 50]",very high,14.526075
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,10.00,10,48.6900,1022.4900,3/2/2019,17:16,4.761905,48.6900,4.4,40,"(0, 10]",very low,15.820631
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,4.761905,1.5920,7.7,30,"(30, 40]",high,15.094544
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,10.00,1,3.2910,69.1110,2/22/2019,15:33,4.761905,3.2910,4.1,30,"(0, 10]",very low,14.526075
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,10.00,7,30.9190,649.2990,2/18/2019,13:28,4.761905,30.9190,6.6,30,"(0, 10]",very low,16.082274

In [266]:
#gives a similar result as the regular GroupBy flow
applied_data = df.head(20).groupby(['Gender','Customer type'])['gross income'].apply(lambda x: x.mean())
applied_data

Gender  Customer type
Female  Member           16.254714
        Normal           18.411500
Male    Member           14.195000
        Normal           21.314833
Name: gross income, dtype: float64